### ISSUE TITLE
Own file endpoint

### ISSUE THREAD

**Issue by sualko** [sualko/cloud_bbb#1]
Don't share files, instead use an own endpoint with a time limited token.

**Comment by joergmschulz** [comment]
is this a duplicate for what I mentioned in my PR for the readme: if a password is enforced for sharing, no conference can be started from the ... menu of files? If not, I'm ready to create just another issue here... (BTW thank you for this awesome integration; my only contribution will be test&document)

**Comment by sualko** [comment]
It's no duplicate, but with an own endpoint we would not depend on the global share settings.

> my only contribution will be test&document

That's equally important :+1:
