### ISSUE TITLE
Invalid API-URL

### ISSUE THREAD

**Issue by julio1501** [sualko/cloud_bbb#100]
**Describe the bug**
I get the error message: "Invalid API-URL" when I try to save the API URL or API Secret. 

**To Reproduce**
1. Input API-URL
2. Input API-secret
3. click save
4. Error: invalid API-URL

**Expected behavior**
Could it be due to the use of a proxy server? Proxy is entered in NC Config and bbb works fine with other frontends. http_proxy and https_proxy are also registred uner system environment

**Screenshots**
![grafik](https://user-images.githubusercontent.com/5425758/99663752-5cb07b80-2a67-11eb-8946-30c8b4a76dfd.png)

**System (please complete the following information):**
 - Browser with version FF 83
 - App version 1.1.
 - Nextcloud version 18.0.6
 - BigBlueButton version 2.2.2
 - Is your BigBlueButton instance working with Greenligh? yes
 - Did you enter your BBB API url and secret? yes

**Nextcloud log:**
NO NC Logs

**Additional context**
behind a proxy Server

**Comment by sualko** [comment]
Please use the [issue template](https://github.com/sualko/cloud_bbb/blob/master/.github/ISSUE_TEMPLATE/bug_report.md), because it provides helpful information to solve your issue.

**Comment by sualko** [comment]
Thanks for filling the issue template. On the screenshot it looks like your url, starts with `'/`. Is this right? It should be a valid url like `https://foobar.com`. Otherwise make sure that your server can make requests to that url (ip restrictions, dns resolution, and so on).

**Comment by julio1501** [comment]
No, the URL starts with `http://` like `https://foobar.com/bigbluebutton/`.
I can access the bbb server over a company Proxy Server.

**Comment by sualko** [comment]
>  Otherwise make sure that your server can make requests to that url (ip restrictions, dns resolution, and so on).

Can you execute `curl https://YOUR_DOMAIN/bigbluebutton/` on your php server and post the result?

**Comment by julio1501** [comment]
`<response>
<returncode>SUCCESS</returncode>
<version>2.0</version>
</response>`

**Comment by sualko** [comment]
Mh, looks good. I just have two other ideas: Can you also try `curl https://YOUR_DOMAIN/bigbluebutton/api/isMeetingRunning?meetingID=randomIDasdf` and do you have php-curl installed? NC should check that, but you never know. To get more information, you can also try to throw the error in https://github.com/sualko/cloud_bbb/blob/40a79d91284b3aa975fe0c1384be916c871ccff7/lib/BigBlueButton/API.php#L243 or to replace the string with something different like `unknown-error`and check the check response in your dev console.

**Comment by julio1501** [comment]
with `curl https://my_domain/bigbluebutton/api/isMeetingRunning?meetingID=randomIDasdf` i get the http error code 500 and the check response from the dev console returns the new string `unknown-error` from the line `243`

**Comment by sualko** [comment]
> i get the http error code 500

That's the issue and it's probably not on our end, because this app is used in a broad range of environments. If you like, you can also set the config values via the command line and try if it's working anyway. Maybe it's an load balancing issue, or something like that. Just execute:

```
./occ config:app:set bbb api.url --value=YOUR_URL
./occ config:app:set bbb api.secret --value=YOUR_SECRET
```

If you find the cause of your issue, it would be nice if you could post it for people with similar issues.

**Comment by julio1501** [comment]
Hi @sualko ,

thanks for your support and the great work.

**Comment by julio1501** [comment]
I reinstalled the bbb machine outside of our restrictive DMZ and everything works fine now.

Thanks

**Comment by sualko** [comment]
Good to hear. Thanks for the update.

**Comment by ranti71** [comment]
Hi! I know, this is closed, but i have same issue. When i use bbb-app with a Nextcloud-server behind NAT, everything works fine. When i use it on a Nextcloud-server behind a reverse proxy, i got the "invalid API URL" message. with curl and w3m i can reach the API-ulr of bbb Server. From nextcloud-server i can only access via proxy and we have no DNS-resolution for external domains. Whole traffic is going through proxy. Every app we installed in Nextcloud are working fine. Proxy is configured in config.php. BBB-Server is not behind a reverse proxy. 
I don#t find any real helping log-entries....
Has anyone an idea? We are strongly recommended to use Nextcloud-server in our reverse proxy infrastructure in cause auf security reasons.
Thnx a lot for yourr help!

**Comment by MaoX17** [comment]
> bigbluebutton/api/isMeetingRunning?meetingID=randomIDasdf

i have same issue
