### ISSUE TITLE
URL to room could not be stored

### ISSUE THREAD

**Issue by baltaner** [sualko/cloud_bbb#102]
**Describe the bug**
Adding Room-Link results in "URL to room could not be stored"
**To Reproduce**
1. in BBB-room view
2. Click on 'Add-Link'
3. See error: "URL to room could not be stored"
(webconference is working perfect! it's only the "room-link"-Icon not working!

**Expected behavior**
Result should be: "Link stored"

**Screenshots**
![link-stored](https://user-images.githubusercontent.com/29839738/99653654-967a8580-2a59-11eb-82b8-ce89be8c21e0.PNG)
![add-link](https://user-images.githubusercontent.com/29839738/99653655-97131c00-2a59-11eb-965f-8b4cda92a622.PNG)
![error](https://user-images.githubusercontent.com/29839738/99653656-97abb280-2a59-11eb-8462-0f81c307ab8f.PNG)

**System (please complete the following information):**
 - Browser Firefox 83.0, Chrome  87.0.4280.66
 - App version [1.1.1]
 - Nextcloud version [19.0.5, 20.0.1, 20.0.2 (runs on ubuntu 20.04 with apache2, php-fpm)]
 - BigBlueButton version [2.2.29]
 - Is your BigBlueButton instance working with Greenligh? yes
 - Did you enter your BBB API url and secret? yes

**Nextcloud log:**
ther are no nextcloud errors in nextloud log!

**Apache log**
```
[proxy_fcgi:error] [pid 98415] [client 10.24.28.1:60655] AH01071: Got error 'Primary script unknown'
```

**Javascript log:**

```
jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 164 globals.js:60:15
jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 168 globals.js:60:15
OC.Util.relativeModifiedDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment 10 util.js:130:10
XHRPUThttps://sembska.de/remote.php/dav/files/wwwadmin/test.url
[HTTP/1.1 404 Not Found 17ms]

jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 8 globals.js:60:15
Could not store room Error: Request failed with status code 404
    exports createError.js:16
    exports settle.js:17
    onreadystatechange xhr.js:69
    exports xhr.js:44
    exports xhr.js:13
    exports dispatchRequest.js:52
    promise callback*l.prototype.request Axios.js:61
    e Axios.js:86
    exports bind.js:9
    n Api.ts:190
    u runtime.js:63
    _invoke runtime.js:293
    A runtime.js:118
    f manager.js:1
    f manager.js:1
    value manager.js:1
    onClick RoomRow.tsx:81
    y dialogs.js:453
    click dialogs.js:459
    jQuery 26
    filepicker dialogs.js:504
    jQuery 6
RoomRow.tsx:88:12
jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
```

**Additional context**
I am running 2 nextcloud instances - one with ldap-auth, the other with nextcloud database users.
The problem ONLY occurs in the instance with ldap-auth.
Any ideas?

**Comment by joergmschulz** [comment]
cannot reproduce here with NV20 and Ldap, even on groupfolders the URL gets created

**Comment by sualko** [comment]
I can't reproduce your issue and I also don't think this is ldap related. Are you sure you have write access to the folder? Make sure it's not a share without write access. You can also check the network tab of your browser dev console for the "store" request. Maybe you find an answer in the response.

**Comment by baltaner** [comment]
too bad to hear that....
yes, I have write access  - no share!
Perhaps it's a problem with remote.php - in network-console manager.js
``
scheme
	https
host
	sembska.de
filename
	/remote.php/dav/files/wwwadmin/t.url
``
my nextxcloud is running in a subfolder - /nextcloud
I think the filename-part should be /nextcloud/remote.php/dav/files/wwwadmin/t.url

**Comment by sualko** [comment]
> my nextxcloud is running in a subfolder - /nextcloud

Nice catch. That's the reason and it should be easy to fix. Thanks for your help to resolve this.

**Comment by baltaner** [comment]
thank you!
It works perfectly now!
