### ISSUE TITLE
Get mp4 recording into Nextcloud

### ISSUE THREAD

**Issue by cadjou** [sualko/cloud_bbb#106]
Hello everyone,

I use the BigBlueButton NextCloud App and this Git https://github.com/tilmanmoser/bbb-video-download to get the MP4 into NextCloud
I make a Git to do that https://github.com/cadjou/bbb_record_in_nextcloud
I want check if all is working good, so if want to try and let me know, in case.

Thank you

**Comment by sualko** [comment]
Thanks for sharing your work with us. Nonetheless I will close this issue in favor of https://help.nextcloud.com/t/get-mp4-recording-into-nextcloud/101153. I think it's the more appropriate place to discuss your scripts.
