### ISSUE TITLE
Tooltips for icons

### ISSUE THREAD

**Issue by aov-arnold** [sualko/cloud_bbb#114]
Currently it is not clear for users what the different icons stand for:
![bbb_nc_tooltips](https://user-images.githubusercontent.com/57179682/104937527-2b442580-59ae-11eb-81bc-359aa1a8bd99.png)

There should be tooltips for each icon as already implemented for "Edit" and "Delete":
- Enter room
- Copy link
- Save link
- Edit name
- Internal/ Public
- Edit max. participant
- Allow recording
- Recording count
- Show recordings

**Comment by sualko** [comment]
Thanks for your report. If you have time it would be great if you could provide those changes in a pull request. You should be able to make those changes even on Github.

**Comment by aov-arnold** [comment]
When I do find the time, I'll try it. How can I add new text snippets to transifex?

**Comment by sualko** [comment]
> How can I add new text snippets to transifex?

Transifex is pulling automatically for new strings.

**Comment by sualko** [comment]
This issues has been fixed in the meantime.
