### ISSUE TITLE
Room starts with non-default User Settings

### ISSUE THREAD

**Issue by sbellm** [sualko/cloud_bbb#116]
**Describe the bug**
We have a global Server Setting for privat chat and shared notice disabled by default.
Opening a room with greenlight, this feature is enabled and chat and notice are disabled, moderator can enable it.
Opening via nextcloud, the feature is enabled by starting.

**To Reproduce**
1. Open BBB Room with NC
2. Open Restrict participant rights, All are enabled by default

**Expected behavior**
Restrict participant rights should enabled / diabled by Server default settings

**System (please complete the following information):**
 - all Browsers
 - Nextcloud 20.05
 - BigBlueButton 2.2.31
 - Is your BigBlueButton instance working with Greenligh? yes
 - Did you enter your BBB API url and secret? yes

**Additional context**

**Comment by sualko** [comment]
> We have a global Server Setting for privat chat and shared notice disabled by default.

Where did you configure that global server setting? Can you post the part of your config?

**Comment by sbellm** [comment]
/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties

There are also a lot ot other settings:

My Settings here are:
# Default Lock Settings
lockSettingsDisableCam=false
lockSettingsDisableMic=false
lockSettingsDisablePrivateChat=true
lockSettingsDisablePublicChat=false
lockSettingsDisableNote=true
lockSettingsHideUserList=false
lockSettingsLockedLayout=false
lockSettingsLockOnJoin=true
lockSettingsLockOnJoinConfigurable=false

**Comment by sualko** [comment]
Thank you for your quick reply. It seams like the php library is setting all settings to false by default. I opened an issue (https://github.com/littleredbutton/bigbluebutton-api-php/issues/54) and a solution is right around the corner. Thanks for reporting this behavior.

**Comment by sbellm** [comment]
No Problem, idea how to fix it manually or hard in code?

**Comment by sualko** [comment]
> idea how to fix it manually or hard in code?

The defaults should be used if you remove the following lines:

https://github.com/littleredbutton/bigbluebutton-api-php/blob/82973d891807de6e264cc0be395868cc041652a0/src/Parameters/CreateMeetingParameters.php#L1101-L1110

You should find this file in `apps/bbb/vendor/littleredbutton/bigbluebutton-api-php/src/Parameters/CreateMeetingParameters.php`.

**Comment by sbellm** [comment]
I did it by hardcoding the defaults in this files, works fine. But thanks for the next patch!
