### ISSUE TITLE
API-URL or secret not configured

### ISSUE THREAD

**Issue by troepfli** [sualko/cloud_bbb#121]
Hi 

I'm running a Nextcloud Intance on my webserver. If I download and activate the bbb integration, I've got the following error in the Nextcloud bbb settings. 

API-URL oder secret (secret phrase) not configured. please contact administrator. 

Is there maybe a depencies I missed?

cheers

**Comment by sualko** [comment]
> This app allows to create meetings with an external installation of BigBlueButton.

Do you have an external installation? Why is no one reading [installation guides](https://github.com/sualko/cloud_bbb#gear-configure-it)?

**Comment by troepfli** [comment]
I searched a bit, but the bbb-conf --secret doesn't work. Maybe its because I tried yunohost in order to test nextcloud on my server. I'll close the issue and try to dig deeper in :)

**Comment by sualko** [comment]
The external dependency is BigBlueButton. This means you need to install BigBlueButton! Next time also please use the issue template.

**Comment by troepfli** [comment]
ok, i thought i could install it out of Nextcloud itself via the store (as you mention in the Install section)

"The easiest way to install this app is by using the Nextcloud app store. If you like to build from source, please continue reading."

**Comment by sualko** [comment]
You can install this app via the Nextcloud store, but as stated this requires an external installation of BigBlueButton. This application is just a client.
