### ISSUE TITLE
Unmute users - allowModsToUnmuteUsers=true

### ISSUE THREAD

**Issue by erichrueger** [sualko/cloud_bbb#122]
In  /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties I can set the option for moderators to be able to unmute users (allowModsToUnmuteUsers=true)
When creating rooms with Greenlight, this option works. However, it doesn't work with rooms created by the Nextcloud-App on the same server.
From what I have read, this option is part of the room creation process (quote from another thread: _you have to enable unmuting in the create\join request...._)
It would bei great, if you could add support for this option to Nextcloud-BBB-App.
We are working with severely disabled students in homeschooling, who are in part unable to control muting and unmuting their microphones.

**Comment by sualko** [comment]
I think this is related to #116. The same workaround described there should also work for you. We are currently refactoring the php library to fix this issue in this app, see https://github.com/littleredbutton/bigbluebutton-api-php/pull/49.

**Comment by erichrueger** [comment]
Thank you. It worked. My colleagues will be happy!

Am Mi., 3. Feb. 2021 um 16:50 Uhr schrieb Klaus <notifications@github.com>:

**Comment by erichrueger** [comment]
DankeVon meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: Klaus <notifications@github.com> Datum: 03.02.21  16:50  (GMT+01:00) An: sualko/cloud_bbb <cloud_bbb@noreply.github.com> Cc: erichrueger <erich.rueger@gmail.com>, Author <author@noreply.github.com> Betreff: Re: [sualko/cloud_bbb] Unmute users - allowModsToUnmuteUsers=true (#122) 
I think this is related to #116. The same workaround described there should also work for you. We are currently refactoring the php library to fix this issue in this app, see littleredbutton/bigbluebutton-api-php#49.

**Comment by erichrueger** [comment]
Thank you. I was writing but not thinking.Von meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: Klaus <notifications@github.com> Datum: 03.02.21  16:50  (GMT+01:00) An: sualko/cloud_bbb <cloud_bbb@noreply.github.com> Cc: erichrueger <erich.rueger@gmail.com>, Author <author@noreply.github.com> Betreff: Re: [sualko/cloud_bbb] Unmute users - allowModsToUnmuteUsers=true (#122) 
I think this is related to #116. The same workaround described there should also work for you. We are currently refactoring the php library to fix this issue in this app, see littleredbutton/bigbluebutton-api-php#49.
