### ISSUE TITLE
App doesn't work with Scalelite loadbalancer

### ISSUE THREAD

**Issue by pielonet** [sualko/cloud_bbb#123]
**Describe the bug**
You can not configure the BBB integration App to make use of Scalelite loadbalancer

**To Reproduce**
1. Go to App configuration
2. Seize Scalelite API Url (https://scalelite.example.com/bigbluebutton/api/) and secret
3. Validate entry
4. Validation error message

**Expected behavior**
The BBB integration App should accept such URLs since Scalelite reproduces the BigBlueButton API in totality so it should be 100% compatible.
The problem arises because the App only accepts URLs finishing with "/bigbluebutton/" and not URLs in the form "/bigbluebutton/api/" which are the only ones enabled in Scalelite.

 - App version 1.1.4
 - Nextcloud version 20
 - Scalelite version 1.0.8
 - Scalelite instance working with Greenlight ? yes
 - Did you enter your Scalelite API url and secret? yes

**Nextcloud log:**

```
REPLACE ME WITH YOUR NEXTCLOUD LOG
```

**Javascript log:**

```
REPLACE ME WITH YOUR JS LOG
```

**Additional context**

**Comment by sualko** [comment]
Thanks for your bug report. We don't test this application against scalelite, but we know that there are people using it without any issues. So far the good news.

> The problem arises because the App only accepts URLs finishing with "/bigbluebutton/" 

Why do think it's the url format? We don't enforce any format, except that it has to start with https.

The only check we are doing is a quick is meeting running call to the api.

> Validation error message

Would be nice to know the error message.

You can also skip the check and set the app config directly via occ or in your js console. E.g.:

```
OCP.AppConfig.setValue('bbb', 'api.url', url);
OCP.AppConfig.setValue('bbb', 'api.secret', secret);
```

**Comment by sualko** [comment]
Any update on this issue?
