### ISSUE TITLE
Where to change the text "BigBlueButton" in the App menu

### ISSUE THREAD

**Issue by jacotec** [sualko/cloud_bbb#124]
Just a short question: In which place/file can this text "BigBlueButton" be changed to something else?

![grafik](https://user-images.githubusercontent.com/3321655/107848727-1ebcbc80-6df6-11eb-93f6-2b1f51344c55.png)

**Comment by sualko** [comment]
It's in [Application.php](https://github.com/sualko/cloud_bbb/blob/e72effbe4c8742275dcc05e61a50233023033c89/lib/AppInfo/Application.php#L67). If you have time it would be nice if you could create a pull request which makes the label configurable. Therefore you have to add a `$name` parameter to the `registerAsNavigationEntry()` and pass it in line 46 with `$config->getAppValue(self::ID, 'app.navigation.name', 'BigBlueButton')`. Afterwards you can change the value via `occ`.

**Comment by jacotec** [comment]
Thank you @sualko for your fast response! That works perfectly.
I'd love to do a PR for this, unfortunately I have no clue about NC apps infrastructure and very limited PHP knowledge. Not sure if I can figure out how to do this.

It would be great to have this configurable as I think I need to redo the change after every update. Maybe someone who knows how to do this can take it, that does not look like a big thing for someone who has knowledge of the NC ecosystem.

**Comment by sualko** [comment]
Limited php knowledge is enough and you don't have to setup a huge dev environment. You can make those changes via github. Just go to the linked file and apply the changes as described. After you have opened the pull request, I'm happy to check it for errors and finalize it.

>  I think I need to redo the change after every update

That's right and with a pr you have to do it only once :smile:
