### ISSUE TITLE
Create room from main menu

### ISSUE THREAD

**Issue by sunjam** [sualko/cloud_bbb#13]
Thanks for working on this!  I'd like to be able to create and configure rooms from the menu menu as opposed to Settings/Personal.  Thanks for considering.
![Screenshot_20200427_134614](https://user-images.githubusercontent.com/1787238/80419224-96345600-888d-11ea-8c9f-dde21ca3435b.png)
  - `Create with BBB`

**Comment by sualko** [comment]
Thanks for testing. :clap:

In my opinion that's a bad idea, because the resulting room is not visible in the file list like all other entries in that list. There are probably other ideas to enhance the creation workflow: default room for every user, temporary room, and so on...
