### ISSUE TITLE
Exception "Could not resolve OCP\Settings\IManager" for Nextcloud 19

### ISSUE THREAD

**Issue by aszlig** [sualko/cloud_bbb#130]
**Describe the bug**
When using `occ app:list` with `bbb` version 1.3.0, an exception is thrown.

**To Reproduce**
1. Install app on Nextcloud 19
2. Run `occ app:list`
3. See error

**Expected behavior**
No error.

**System (please complete the following information):**
 - App version [1.3.0]
 - Nextcloud version [19.0.9.1]

**Nextcloud log:**
```json
{
  "Exception": "OCP\\AppFramework\\QueryException",
  "Message": "Could not resolve OCP\\Settings\\IManager! Class can not be instantiated",
  "Code": 0,
  "Trace": [
    {
      "file": "/nix/store/2apgn99bsdzp42ivwfknx7h9n4xnj5y1-nextcloud-19.0.9.1/lib/private/AppFramework/Utility/SimpleContainer.php",
      "line": 116,
      "function": "resolve",
      "class": "OC\\AppFramework\\Utility\\SimpleContainer",
      "type": "->",
      "args": [
        "OCP\\Settings\\IManager"
      ]
    },
    {
      "file": "/nix/store/2apgn99bsdzp42ivwfknx7h9n4xnj5y1-nextcloud-19.0.9.1/lib/private/ServerContainer.php",
      "line": 149,
      "function": "query",
      "class": "OC\\AppFramework\\Utility\\SimpleContainer",
      "type": "->",
      "args": [
        "OCP\\Settings\\IManager",
        true
      ]
    },
    {
      "file": "/nix/store/2apgn99bsdzp42ivwfknx7h9n4xnj5y1-nextcloud-19.0.9.1/lib/private/AppFramework/DependencyInjection/DIContainer.php",
      "line": 388,
      "function": "query",
      "class": "OC\\ServerContainer",
      "type": "->",
      "args": [
        "OCP\\Settings\\IManager",
        true
      ]
    },
    {
      "file": "/nix/store/2apgn99bsdzp42ivwfknx7h9n4xnj5y1-nextcloud-19.0.9.1/apps/bbb/lib/AppInfo/Application.php",
      "line": 56,
      "function": "query",
      "class": "OC\\AppFramework\\DependencyInjection\\DIContainer",
      "type": "->",
      "args": [
        "OCP\\Settings\\IManager"
      ]
    },
    {
      "file": "/nix/store/2apgn99bsdzp42ivwfknx7h9n4xnj5y1-nextcloud-19.0.9.1/apps/bbb/lib/AppInfo/Application.php",
      "line": 50,
      "function": "registerAsPersonalSetting",
      "class": "OCA\\BigBlueButton\\AppInfo\\Application",
      "type": "->",
      "args": []
    },
    {
      "function": "__construct",
      "class": "OCA\\BigBlueButton\\AppInfo\\Application",
      "type": "->",
      "args": [
        []
      ]
    },
    {
      "file": "/nix/store/2apgn99bsdzp42ivwfknx7h9n4xnj5y1-nextcloud-19.0.9.1/lib/private/AppFramework/Utility/SimpleContainer.php",
      "line": 84,
      "function": "newInstanceArgs",
      "class": "ReflectionClass",
      "type": "->",
      "args": [
        [
          []
        ]
      ]
    },
    {
      "file": "/nix/store/2apgn99bsdzp42ivwfknx7h9n4xnj5y1-nextcloud-19.0.9.1/lib/private/AppFramework/Utility/SimpleContainer.php",
      "line": 101,
      "function": "buildClass",
      "class": "OC\\AppFramework\\Utility\\SimpleContainer",
      "type": "->",
      "args": [
        {
          "name": "OCA\\BigBlueButton\\AppInfo\\Application",
          "__class__": "ReflectionClass"
        }
      ]
    },
    {
      "file": "/nix/store/2apgn99bsdzp42ivwfknx7h9n4xnj5y1-nextcloud-19.0.9.1/lib/private/AppFramework/Utility/SimpleContainer.php",
      "line": 116,
      "function": "resolve",
      "class": "OC\\AppFramework\\Utility\\SimpleContainer",
      "type": "->",
      "args": [
        "OCA\\BigBlueButton\\AppInfo\\Application"
      ]
    },
    {
      "file": "/nix/store/2apgn99bsdzp42ivwfknx7h9n4xnj5y1-nextcloud-19.0.9.1/lib/private/ServerContainer.php",
      "line": 149,
      "function": "query",
      "class": "OC\\AppFramework\\Utility\\SimpleContainer",
      "type": "->",
      "args": [
        "OCA\\BigBlueButton\\AppInfo\\Application",
        true
      ]
    },
    {
      "file": "/nix/store/2apgn99bsdzp42ivwfknx7h9n4xnj5y1-nextcloud-19.0.9.1/apps/bbb/appinfo/app.php",
      "line": 5,
      "function": "query",
      "class": "OC\\ServerContainer",
      "type": "->",
      "args": [
        "OCA\\BigBlueButton\\AppInfo\\Application"
      ]
    },
    {
      "file": "/nix/store/2apgn99bsdzp42ivwfknx7h9n4xnj5y1-nextcloud-19.0.9.1/lib/private/legacy/OC_App.php",
      "line": 266,
      "args": [
        "/nix/store/2apgn99bsdzp42ivwfknx7h9n4xnj5y1-nextcloud-19.0.9.1/apps/bbb/appinfo/app.php"
      ],
      "function": "require_once"
    },
    {
      "file": "/nix/store/2apgn99bsdzp42ivwfknx7h9n4xnj5y1-nextcloud-19.0.9.1/lib/private/legacy/OC_App.php",
      "line": 155,
      "function": "requireAppFile",
      "class": "OC_App",
      "type": "::",
      "args": [
        "bbb"
      ]
    },
    {
      "file": "/nix/store/2apgn99bsdzp42ivwfknx7h9n4xnj5y1-nextcloud-19.0.9.1/lib/private/legacy/OC_App.php",
      "line": 128,
      "function": "loadApp",
      "class": "OC_App",
      "type": "::",
      "args": [
        "bbb"
      ]
    },
    {
      "file": "/nix/store/2apgn99bsdzp42ivwfknx7h9n4xnj5y1-nextcloud-19.0.9.1/lib/private/Console/Application.php",
      "line": 127,
      "function": "loadApps",
      "class": "OC_App",
      "type": "::",
      "args": []
    },
    {
      "file": "/nix/store/2apgn99bsdzp42ivwfknx7h9n4xnj5y1-nextcloud-19.0.9.1/console.php",
      "line": 84,
      "function": "loadCommands",
      "class": "OC\\Console\\Application",
      "type": "->",
      "args": [
        {
          "__class__": "Symfony\\Component\\Console\\Input\\ArgvInput"
        },
        {
          "__class__": "Symfony\\Component\\Console\\Output\\ConsoleOutput"
        }
      ]
    },
    {
      "file": "/nix/store/2apgn99bsdzp42ivwfknx7h9n4xnj5y1-nextcloud-19.0.9.1/occ",
      "line": 11,
      "args": [
        "/nix/store/2apgn99bsdzp42ivwfknx7h9n4xnj5y1-nextcloud-19.0.9.1/console.php"
      ],
      "function": "require_once"
    }
  ],
  "File": "/nix/store/2apgn99bsdzp42ivwfknx7h9n4xnj5y1-nextcloud-19.0.9.1/lib/private/AppFramework/Utility/SimpleContainer.php",
  "Line": 103,
  "CustomMessage": "--"
}
```

**Additional context**
This has been found as part of an automated test suite, the full build log can be found here:

https://headcounter.org/hydra/log/8pzac4wvn4s3hmadb1cnjib8sjnx35bc-vm-test-run-nextcloud-upgrade.drv

**Comment by sualko** [comment]
Thanks for your report. The [`OCP\\Settings\\IManager`](https://github.com/nextcloud/server/blob/master/lib/public/Settings/IManager.php) exists since Owncloud 9 and this app runs without any issues on hundreds of installations. Also our [tests](https://github.com/sualko/cloud_bbb/actions/workflows/php-test.yml), which enable the app, are not throwing any error. Therefore I think it's more likely that the error is coming form your test setup. I don't want to say that it is impossible, but unlikely :-)

If you have further information how this can be analysed, I'm glad to hear it.

**Comment by DonCarlosGraz** [comment]
We are also affected by this issue:
- App version [1.3.0]
- Nextcloud version [19.0.9.1]
- Log entry "Could not resolve OCP\\Settings\\IManager! Class can not be instantiated"

**Comment by sualko** [comment]
Are you installing the app from the app store?

**Comment by DonCarlosGraz** [comment]
yes and additionally I got the information, that we did a clean, new installation and the problem still occurs.

**Comment by DonCarlosGraz** [comment]
Additional info: the command `php -f occ app:enable bbb` shows us `bbb enabled`, but `php -f occ app:list` shows the app in the disabled list

**Comment by DonCarlosGraz** [comment]
I can also reproduce this issue with workflows: 
https://github.com/DonCarlosGraz/cloud_bbb/runs/2167206462?check_suite_focus=true

I've also added a list command - the app will be show in the disabled section:
https://github.com/DonCarlosGraz/cloud_bbb/commit/b58b0ad9134d6bbe67a365cd5354b65cdcbdcbca

![bbb-app-disabled](https://user-images.githubusercontent.com/10727555/112013195-258fcb00-8b2a-11eb-9647-435783d91cea.png)

**Comment by aszlig** [comment]
@sualko:
> Therefore I think it's more likely that the error is coming form your test setup. I don't want to say that it is impossible, but unlikely :-)

I'm not using the app myself, so from my PoV it'd be fine to exclude the app in my tests, but since the error did show up since https://github.com/aszlig/avonc/commit/7fe83217e7fe5be02ea6711131d9b6836f524e7f (which includes the update from `bbb` 1.2.0 to 1.3.0) and I'm also testing almost all other apps in the Nextcloud App Store, I decided to report it anyway. The [test in question](https://github.com/aszlig/avonc/blob/b1acbced497e4fe1caaa12eb56edb5fc2873121e/tests/upgrade.nix) also uses *exactly* the same initial state on every run so if it's a general error with my test setup, other apps should fail as well.

> If you have further information how this can be analysed, I'm glad to hear it.

Bisected the issue to commit f78fd5c47efc7a0135f1352c0bfac6c233420a51 and I think https://github.com/nextcloud/server/commit/770d12d1915dad746d75ba0b23235b75cbe7d1a2 might be the reason why `\OCP\Settings\IManager` can't be resolved via the AppFramework's "Container" mechanism. Note however, that I just did a small `git log -p` on a few files and thus haven't dug very much into it. IIUC, using `\OC\Settings\Manager` instead of `\OCP\Settings\IManager` should work for both NC 19 and NC 20.

@DonCarlosGraz:
> I can also reproduce this issue with the test workflows:
> https://github.com/DonCarlosGraz/cloud_bbb/runs/2167206462?check_suite_focus=true

Not sure whether this is really the same error, although the behaviour of `app:list` looks like it. Did you try enabling error logging for the PHP CLI?

**Comment by DonCarlosGraz** [comment]
@aszlig I just made a fork from the repo and added the `app:list` command (https://github.com/DonCarlosGraz/cloud_bbb/commit/b58b0ad9134d6bbe67a365cd5354b65cdcbdcbca) and then run the workflows.
But I can see that `XDEBUG_MODE` is set to `coverage` (https://github.com/DonCarlosGraz/cloud_bbb/blob/b58b0ad9134d6bbe67a365cd5354b65cdcbdcbca/.github/workflows/php-test.yml#L24)

**Comment by DonCarlosGraz** [comment]
I can confirm that changing of `\OCP\Settings\IManager` to `\OC\Settings\Manager` in `lib/AppInfo/Application.php` as suggested above solves the problem.

**Comment by ukretschmer** [comment]
I also can confirm this Bug. I upgraded Nextcloud 19.0.4 to 19.0.10 and after the upgrade the log contains the mentioned error. Also following indicators in GUI:

- all bbb settings pages wasn't reachable
- app listed as disabled

I also tryed the above patch, which partly works. After applying the patch I was able to enable the app (console and app-gui) without getting an error. The general bbb settings page was reachable. The room management was reachable if set to show up in app navigation but didn't showed up in user settings.

Finally I had to roll back to 1.2.0.

**Comment by sualko** [comment]
It really annoys me that I can't reproduce this bug which is obstructing that many people. 

> I can confirm that changing \OCP\Settings\IManager to \OC\Settings\Manager in lib/AppInfo/Application.php as suggested above "solves" the installation/enable problem.

This is a fix which I can't merge, because it violates NC policies. I will try to install this app on a fresh system on the weekend. Maybe I'm lucky and I get the error too.

It would be helpful if everyone could post the OS, PHP and Nextcloud version.

**Comment by sualko** [comment]
Maybe someone can try to rewrite the related part to this code style: https://github.com/nextcloud/external/blob/master/lib/AppInfo/Application.php

**Comment by DonCarlosGraz** [comment]
> This is a fix which I can't merge, because it violates NC policies.

From my point of view this was just a try, than a real fix.

> It would be helpful if everyone could post the OS, PHP and Nextcloud version.

Debian 10, PHP 7.3, NC 19.0.9.1

Note: We recently upgraded to NC 20.x and the problem is gone.

**Comment by sualko** [comment]
Hi everyone. I can finally reproduce this issue on a fresh installation of Nextcloud 19. Therefore I should be able to fix this soon. Many thanks for the patience.

**Comment by sualko** [comment]
I don't fully understand the issue, but I added a workaround. This should be fine, since NC 19 is eol in a few month.
