### ISSUE TITLE
Deleting a user removes also shared rooms 

### ISSUE THREAD

**Issue by Smith-fms** [sualko/cloud_bbb#131]
Erst auf Deutsch, ich bin nicht so sicher in englisch.

Wir haben einen User angelegt. Dieser hatte einen Schreibfehler. Der Kollege hat diesem aber bereits einige Räume geteilt (inkl. Admin-Rechte damit auch in der Raumverwaltung angezeigt.)

Die Räume waren nach dem Löschen des Nutzers (aus der Nextcloud) ebenfalls gelöscht, obwohl nur geteilt.

Short on english:

Deleting a user in NC even delete all shared rooms which this user got shared.

**Comment by sualko** [comment]
I can reproduce it and will provide a fix as soon as I have time. Thanks for reporting this :+1:
