### ISSUE TITLE
Option limit to group missing since 1.3.0

### ISSUE THREAD

**Issue by sushifrick** [sualko/cloud_bbb#135]
**Describe the bug**
Since the update to version 1.3.0 we are not able to limit the app to a user group anymore, this was able before.

**To Reproduce**
1. Install Update to 1.3.0
2. Try to limit to a group in the App menu

**Expected behavior**
The button "limit to group" is available and limits access to the app to a user gloup.

**System (please complete the following information):**
 - Google Chrome Version 89.0.4389.90 (Official Build) (64-bit)
 - App version 1.3.0
 - Nextcloud version 21.0.0
 - BigBlueButton version: 2.2.35
 - Is your BigBlueButton instance working with Greenlight? yes
 - Did you enter your BBB API url and secret? yes

**Comment by sualko** [comment]
That was intentionally, because if you limit the app to a specific group, members of that group are also not able to join public rooms. To get the same functionality set the default room limit to 0 in the admin settings and add exceptions for the groups which should be able to create groups.
