### ISSUE TITLE
Generalize this addons for other solutions (galene, jitsi, etc.)

### ISSUE THREAD

**Issue by b3** [sualko/cloud_bbb#138]
This option is awesome and I really would like to thank its creator. We use since some day in a academic society. I will definitively buy a ko-fi (as an individual) to you.

What is really nice is the simplicity of the UI and the efficiency of the work done. I think it could be even better if the substance of it could be ported to a generic @nextcloud add-on so that other *equivalent* tool could be integrated in the same way (I mean for instance [galene](https://galene.org/), [jitsi](https://jitsi.org/jitsi-meet/) or even Zoom).

Choice of which tool to integrate could be done in the admin settings and the only feature that should be adapted (from a user point of view) would be the room settings.

That could help considering Nextcloud as the main entry for any organisation.

**Comment by sualko** [comment]
Thanks for the kind words. Currently this is out of scope for me, because I like the Unix philosophy of "do one thing well". Another reason why this is out of scope is, that it requires a giant overhead. Nonetheless if you have time... PR are always welcome.
