### ISSUE TITLE
Display error if room creation fails

### ISSUE THREAD

**Issue by sunjam** [sualko/cloud_bbb#14]
I'd like to kindly request an error of some sort be displayed if room creation fails.

Thanks!

**Comment by sualko** [comment]
Please specify what you mean by "room creation".

**Comment by sunjam** [comment]
I attempted to create a room and as far as I can tell it did not work, but I did not receive any sort of confirmation or error stating what happened.  Nothing happened.

**Comment by FlavioBill** [comment]
Hi... try to help... during inset in oc_bbb_room there is an error:
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'INSERT INTO `oc_bbb_rooms` (`uid`, `name`, `welcome`, `max_participants`, `attendee_password`, `moderator_password`, `record`, `user_id`) VALUES(?, ?, ?, ?, ?, ?, ?, ?)' with params ["XXXXXXXXXXX", "MyRoom", "", 0, "yyyyyyyyyyyyyyyyy", "zzzzzzzzzzzzzzzzzzzzzz", false, "myadmin"]: SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'record' at row 1

Seems that false is not correctly understood by the instert...

So ther room is not inserted in database..

**Comment by sualko** [comment]
@FlavioBill This has already be fixed, see #6

@sunjam This could definitely be enhanced.

**Comment by FlavioBill** [comment]
Thanks..
I have the version published in NextCloud App Store  maybe this version is obsolete...
I try to take app direclty by git
:-)
