### ISSUE TITLE
muteOnStart is set to false, although not configurable

### ISSUE THREAD

**Issue by bpcurse** [sualko/cloud_bbb#141]
**Describe the bug**
The `create` API call contains `muteOnStart=false`, although the behavior is not configurable in the app.
This overrides default server settings in bigbluebutton.properties (if set to `muteOnStart=true`).

**To Reproduce**
1. Set your BBB Server default to `muteOnStart=true` in `/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties`
2. Restart BBB
3. Create a Room using the app
4. Join the Room -> Microphone is not muted on start

**Expected behavior**
Server default should not be overridden as long as there is no way in the app to select how the room should be created.
Do not send muteOnStart GET parameter in API string at all.

**System (please complete the following information):**
 - Browser with version [e.g. chrome, safari] Firefox 87.0
 - App version [e.g. 0.1.0] 1.3.0
 - Nextcloud version [e.g. 18.0.1] 20.0.8
 - BigBlueButton version [e.g. 2.2.9] 2.2.36
 - Is your BigBlueButton instance working with Greenlight? yes
 - Did you enter your BBB API url and secret? yes

**Comment by jvinolas** [comment]
It seems that setJoinMuted it is still hardcoded to false?

https://github.com/sualko/cloud_bbb/blob/master/lib/Service/RoomService.php#L91
