### ISSUE TITLE
To correctly translate "save url to..."

### ISSUE THREAD

**Issue by klorydryk** [sualko/cloud_bbb#142]
Cloud_BBB v1.3.0
Nextcloud 21.0.1

The third icon "link" should not be, as "copy in the clipboard" or "Copier dans le presse-papier" in french, but "save url to..."
![image](https://user-images.githubusercontent.com/1232047/114910714-830ff280-9e1e-11eb-9c95-93ec7387148b.png)

**Comment by sualko** [comment]
Thanks for pointing this out.

Since it seams that it's correct in the code, you should report and/or fix this on [Transifex](https://www.transifex.com/nextcloud/nextcloud/).

https://github.com/sualko/cloud_bbb/blob/0c3636da37bb2049b88b8209d8e9bada3ef649c1/ts/Manager/RoomRow.tsx#L195-L206

**Comment by klorydryk** [comment]
Since the translation of 'Save as file' in transifex is "Enregistrer dans un fichier", which is correct but not what is displayed in the UI, it seems the problem is elsewhere.

**Comment by sualko** [comment]
It seams it was fixed 2 weeks ago on Transifex and will therefore included in the next release :tada:
