### ISSUE TITLE
app name does not change when set with occ

### ISSUE THREAD

**Issue by rasos** [sualko/cloud_bbb#145]
**Describe the bug**

When setting the app name, I would expect it is shown with that name in the app menu for users. Instead, it shows `Forms | Polls | BigBlueButton`. Also when toggling to showing the app in setting the name is still `BigBlueButton`.

**To Reproduce**

       # sudo -u www-data php ./occ config:app:set bbb app.navigation.name --value "Classteaching"
       Config value app.navigation.name for app bbb set to Classteaching

**Expected behavior**

Menu should list `Forms | Polls | Classteaching`. 

**Screenshots**

![Screenshot_2021-04-21_21-11-35](https://user-images.githubusercontent.com/485723/115608208-42b0e880-a2e6-11eb-92f6-1b33f4b864e5.png)

**System (please complete the following information):**
 - App version 1.2.0
 - Nextcloud version 18.0.14
 - BigBlueButton version [e.g. 2.2.31]
 - Is your BigBlueButton instance working with Greenlight? yes
 - Did you enter your BBB API url and secret? yes

**Nextcloud log:**   

no relevant logs

**Comment by sualko** [comment]
Thanks for your request. This feature is only available since 1.3 :wink:
