### ISSUE TITLE
Server settings to hide presentation and chat at start are ignored since app version 1.4.0

### ISSUE THREAD

**Issue by jacotec** [sualko/cloud_bbb#147]
**Describe the bug**
My BBB server is configured to hide the presentation and public chat for every user who joins a room, the user list is always shown by default. That worked flawlessly until version 1.4.0 of the app.

By updating to 1.4.0, this broke for all users and all rooms!

There is a new per-room-option "Clean Layout", but this hides everything including the userlist. And I'd need to inform all users to change all their rooms, telling all conference participants that they need to enable the userlist manually.

**To Reproduce**
1. Configure the BBB-Server to hide presentation and public chat and to show the user list
2. Join any room as moderator, owner or guest
3. The server settings are ignored: Presentation, chat and user list are all shown although differently configured on the server 

**Expected behavior**
The server wide settings should be respected!

**System (please complete the following information):**
 - Browser with version [e.g. chrome, safari]: Any browser
 - App version [e.g. 0.1.0]: 1.4.0
 - Nextcloud version [e.g. 18.0.1]: 21.0.1
 - BigBlueButton version [e.g. 2.2.9]: 2.2.36
 - Is your BigBlueButton instance working with Greenligh? yes
 - Did you enter your BBB API url and secret? yes

**Additional context**
Is there a quick workaround for the issue? Otherwise I need to downgrade back to 1.3.0.

**Comment by sualko** [comment]
Thanks for pointing this out. Server vs Nextcloud settings is always hard.

**Comment by sualko** [comment]
I will release a bug fix tomorrow. Meanwhile you should be able to change the lines by hand.

**Comment by jacotec** [comment]
@sualko I already did this ;-)
Thank you for the turbo fix!
