### ISSUE TITLE
Copy direct shares for video files

### ISSUE THREAD

**Issue by kaystrobach** [sualko/cloud_bbb#148]
**Is your feature request related to a problem? Please describe.**

As a teacher i want to access the direct download url of an audio/video file directly, in order to include it into @bigbluebutton s manged viewing / listening feature in my conference room.

**Describe the solution you'd like**

Option to copy a path, i could directly include in bbb for the duration of the room existence.

**Describe alternatives you've considered**

* nextcloud share
* Youtube

**Additional context**

**Comment by joergmschulz** [comment]
That's already possible:
from the FILES view in your nextcloud, press the ... menu.
You'll find your configured BBB rooms.
Just select the one you want to enter - on entering, the file will be uploaded if the room isn't already open.

**Comment by kaystrobach** [comment]
Will check that with mp4 and mp3 thank you.

Thought it just works with presentations and office documents.

**Comment by kaystrobach** [comment]
Here are my findings:

## 1. Upload via Context Menu fails, as not possible to upload non slides:

https://user-images.githubusercontent.com/1185776/116192501-3c7b9b80-a72e-11eb-9170-c00395e34dbd.mp4

<img width="1361" alt="2021-04-27_07-54-28" src="https://user-images.githubusercontent.com/1185776/116192527-46050380-a72e-11eb-9da1-7c8a098bb17e.png">

## 2. Pasting the Link via Inspector fails, as the file is still protected

<img width="1679" alt="2021-04-27_07-55-36" src="https://user-images.githubusercontent.com/1185776/116192622-67fe8600-a72e-11eb-8bd5-d1d3770466ad.png">

https://user-images.githubusercontent.com/1185776/116192784-9b411500-a72e-11eb-88ef-712be886b67f.mp4

## 3. Workaround via sharing

#. create public share
#. use inspector to fetch the uri
#. paste it into BBB

Try one fails due to wrong file ending:

https://user-images.githubusercontent.com/1185776/116193123-27ebd300-a72f-11eb-87d4-3a135382e5a8.mp4

Working solution append `/1.mp4` or `1.mp3`

https://user-images.githubusercontent.com/1185776/116193310-700af580-a72f-11eb-89b7-288035b496c3.mp4

## 4. Expected behaviour:

#. find a audio/video file (mp3 or mp4)
#. get a public link to the file directly in nextcloud (which may last for 2h or so by default)
#. make it possible to share the link via BBB like in the following youtube video

https://user-images.githubusercontent.com/1185776/116192829-b0b63f00-a72e-11eb-9feb-e795657c9857.mp4

**Comment by kaystrobach** [comment]
After some more research an easier solution was found:

1. create a public share of the file
2. copy the link of the share
3. open the link in the browser
4. in the upper right corner right click the download button
5. in the context menu "safe link address"
6. switch to bbb
7. add external video and paste the url from the clipboard

https://user-images.githubusercontent.com/1185776/116237779-f2f87400-a760-11eb-8edf-4b5cece9dc58.mp4

The question is - if and how can we make that process easier - maybe this should be solved in nextcloud itself and not in this extension.

**Comment by sualko** [comment]
Just a tip for your current work flow: You only have to add `/download` to every share url to get the "raw" link which is working in BBB.

Back to your issue: I understand your problem, but I'm not sure if this is something we should fix in this app. We already use such short term shares for the "start with file" feature, but it would not feel right to me. Maybe you can ask NC directly and come back if you got a response.

**Comment by kaystrobach** [comment]
Agree - imho we can close it for now, but please don’t delete the issue - maybe someone find the findings useful.

**Comment by kaystrobach** [comment]
Maybe it makes sense to add it to the docs 😊

**Comment by sualko** [comment]
> Maybe it makes sense to add it to the docs

Pull request to the Troubleshooting section in the readme welcome. Can also be done via the Web Ui (little pen icon).

**Comment by kaystrobach** [comment]
I know - will do that.
