### ISSUE TITLE
Connecting to Meeting fail

### ISSUE THREAD

**Issue by FlavioBill** [sualko/cloud_bbb#15]
Hi...
I update with version 0.1.1, now the creation of Meeting Room i OK.. and also I can start the meeting. The trouble is invite other person. The link correctly display the request for a name, but after I entered it and press the arrow I constantly return on the "presentation" page.

Have a nice day (and thanks for your work)
Flavio

**Comment by sualko** [comment]
What is the presenter page? Can you check your js console (ctrl+shift+I) for errors or warnings?

**Comment by sualko** [comment]
closed due to inactivity
