### ISSUE TITLE
Downgrade after 1.4 update not possible

### ISSUE THREAD

**Issue by spreeni151** [sualko/cloud_bbb#150]
Hi,

today I took a look on the new 1.4 version. In my opinion the new options are a bit too much and seems to confuse our teachers a bit. 

We have configured our BBB system in such a way that only the chat is hidden, but the guests part is visible. For us this was the best configuration - but this can no longer be started at all.

Now I wanted to go back to 1.3. I loaded the bbb-v1.3.0.tar.gz file and extracted it with tar -xf in the apps folder. Then activated with php occ app: enable bbb.

Now, when creating a room I only get the message "Servererror - Error: Request failed with status code 500"
So I cannot go back to the previous version. Can someone please help me out of this trouble?

Many Thanks!

Frank

**Comment by sualko** [comment]
> We have configured our BBB system in such a way that only the chat is hidden, but the guests part is visible.

This has already be fixed in https://github.com/sualko/cloud_bbb/commit/bc3f64c4c3941a5cd4a9b8f3f81abdea48ffda57 and will be released probably tomorrow. You can also change those lines by hand.

> So I cannot go back to the previous version

It is possible, but you have to change some db entries. In the best case you have a backup. No further support for that. Sorry.

**Comment by spreeni151** [comment]
Thank you very much, with that code rooms are looking like they did before. So there is no need to switch back to version 1.3.
Anyway, maybe it is time to sort the options in 'options-window'. Don't get me wrong, I'm very happy about the possibility of new flexible configurations - but many options also have the potential to confuse users. Perhaps in the future we can create presets with which options can be combined and default settings for pre-configuring rooms by Admins. 
Thanks again for your fast help, that really saves me! :-)
Frank
