### ISSUE TITLE
Room-Setting to mute joining Users by default

### ISSUE THREAD

**Issue by Lukeva** [sualko/cloud_bbb#152]
**Is your feature request related to a problem? Please describe.**
Currently on our server all Users joining a Meeting are unmuted after joining as default, which causes disruptions in larger Meetings, when there is a presentation going on.

**Describe the solution you'd like**
It would be great if in the Room Setting there would be an option to disable the microfone of new users joining the room.

**Describe alternatives you've considered**
It should be possible to mute newly joining users as a server-standard, but then it wouldn´t be possible to join as quickly as when it were enabled on joining, especially when using Breakout-Sessions.

**Additional context**
In Greenlight this is an option in the Room settings, which is why I hope this might be comparably easy to implement. However unfortunately I lack the programming knowledge myself, so if someone thinks this would be a good idea, you would earn a lot of gratitude from me! And this should definitely be mentioned as well: Thanks to all people contributing to this very awesome extension! I am so very grateful, for this fantastic ease of our the worklife in our NGO!

**Comment by sualko** [comment]
I think this would be a great extension. If you have time a pr would be appreciated. It should be not that much work, since most parts could be copied from similar settings.
