### ISSUE TITLE
Default room settings bug

### ISSUE THREAD

**Issue by maumanug9** [sualko/cloud_bbb#155]
**Describe the bug**
The default settings for new rooms are not set as intended. 
The option "Listen only option" is not set and the option "Skip media check before usage" is set,
if you  open the rooms settings right after creating the room.
If you don't open the settings and reload the page where you maintain the rooms the options are correctly set.

**To Reproduce**
1. Create new Room
2. Open Settings
3. Listen only option -> on  --- Skip media check before usage -> off
4. Now these settings will be saved into DB

Workaround:
1. Create new Room
2. Reload Page
3. Open Settings 
   -> Listen only option -> off
   -> Skip media check before usage -> on

**Expected behavior**
Correct room settings without reload of the page

**System (please complete the following information):**
 - Browser with version [e.g. chrome, safari]: Firefox, Chrome, iOS Safari
 - App version [e.g. 0.1.0]: 1.4.1
 - Nextcloud version [e.g. 18.0.1]: 20.0.9
 - BigBlueButton version [e.g. 2.2.9]: where can this be seen?
 - Is your BigBlueButton instance working with Greenligh? yes
 - Did you enter your BBB API url and secret? yes

**Comment by sualko** [comment]
Sorry, that I didn't respond, but I was busy. If you have time it would be great if you could test the fix.

**Comment by maumanug9** [comment]
No problem. I tested it and it works as expected. Thank you.

**Comment by sualko** [comment]
Great. Thanks for testing. Will release a bug fix version asap.
