### ISSUE TITLE
ScaleLite loadbalacer does not work with bbb app

### ISSUE THREAD

**Issue by spreeni151** [sualko/cloud_bbb#156]
Hi,

I tried to configure the bbb app to use my scalelite array, but this seems to be not possible. It is exactly the same problem @pielonet discribed here: https://github.com/sualko/cloud_bbb/issues/123

My scalelite server is working, I testet it with Api-Mate (https://mconf.github.io/api-mate/). So I am shure, url and secret are o.k. and working. Then I copied the scalelite url (https://scalelite.example.com/bigbluebutton/api/) and the loadbalancer secret into admin settings of the bbb app.

After pressing 'save' I got the small red message, wrong secret or url. But I KNOW that these values are right, because they are working within Api-Mate. So I opened the database of my server and changed the values api.url and api.secret with the ones of my scalelite server. Now they are listed correctly in admin settings, but my rooms still do not open. I got a nextcloud error message (internal server error).

You wrote that there are users that got scalelite working with your bbb-app, so what do I wrong?

I installed my scalelight-server in this way: https://githubmemory.com/repo/manishkatyan/bbb-scalelite

And again, it is working within Api-Mate.

Regards, Frank

**Comment by spreeni151** [comment]
Any ideas of this? Maybe it could be helpful if someone who is using scalelite together with nextcloud post his bbb app version? Could be a bug in the current version...

**Comment by sualko** [comment]
If you enter the url and secret in the admin settings we make a dummy "is meeting running" request. To debug this further you should try calling the same endpoint from your server with curl. So use api-mate to get the `isMeeting` running url for a random room `curl -v https://test-install.blindsidenetworks.com/bigbluebutton/api/isMeetingRunning?meetingID=random-4310246&checksum=740e8865dae912978556dc7b5e5a32c760bf2749` and check the response. If this doesn't help throw the error in https://github.com/sualko/cloud_bbb/blob/master/lib/BigBlueButton/API.php#L268 and check your NC log.

**Comment by spreeni151** [comment]
Thank you @sualko , that put me on the right track. I have now done it differently than it is described in the Scalelite documentation. I tried the url like "https://scalelite.server.url/bigbluebutton/" **without** "api/". So it worked!
The BBB app behaves somewhat differently than e.g. the Moodle integration and, as described, differently from the Scalelite documentation. But ... no matter, that's how it works :-). 
I think it would make sense to put a sentence on the ScaleLite integration in the Readme.md. 
Thanks and have a nice day!

**Comment by sualko** [comment]
If you call `bbb-conf --secret` it is printing the url without `api/` and for this reason probably also the official php client is requiring the url without that suffix. If you could create a pull request to add a hint to the troubleshooting section, that would be awesome.

**Comment by spreeni151** [comment]
>  If you could create a pull request to add a hint to the troubleshooting section, that would be awesome.
I tried and hope I did it right. Never done this before.

btw: I also requested to change the recommendation for sharing mp4 and mp3 files to the more common adresses /download?.mp4 and /download?.mp3 . This had nothing to do with the topic but the other way with /download/file.mp4 is not working correct.
