### ISSUE TITLE
Can't connect to Scalelight with 64 character secret

### ISSUE THREAD

**Issue by thorsten-l** [sualko/cloud_bbb#160]
**Describe the bug**
Can't connect to Scalelight with 64 character secret. "API-Geheimnis ist ungültig"

**System (please complete the following information):**
 - Chrome/91.0.4472.77
 - App version 1.4.1
 - Nextcloud version 21.0.2
 - BigBlueButton version 2.3.3
 - Is your BigBlueButton instance working with Greenlight? yes  and Moodle and Stud.IP
 -    I get the API URL and API Secret from the Greenlight instance
 - Did you enter your BBB API url and secret? yes

**Nextcloud log:**
```
No Errors
```

**Javascript log:**
```
No Errors
```

**Comment by sualko** [comment]
Did you check our [troubleshooting section](https://github.com/sualko/cloud_bbb#pick-troubleshooting)?

**Comment by thorsten-l** [comment]
Sorry, it was an network issue. Everything works fine.
