### ISSUE TITLE
Column "oc_bbb_rooms"."record" is type Bool and also NotNull, so it can not store "false".  

### ISSUE THREAD

**Issue by NelsoCruz** [sualko/cloud_bbb#164]
**The bug**
I Can´t install BBB on nextcloud 22.0.0

always apear this error: Column "oc_bbb_rooms"."record" is type Bool and also NotNull, so it can not store "false".  

See the pecture to understand what I am talking about

 - Browser with version [chrome, safari]
 - Nextcloud version [22.0.0]
 - BigBlueButton version [1.4.2]

**Comment by NelsoCruz** [comment]
![bug bbb](https://user-images.githubusercontent.com/87093884/124863587-3c5e0e80-dfaf-11eb-8086-681477cc690e.PNG)

**Comment by sualko** [comment]
Thanks for your report. Since we do not support NC 22 yet, this is somewhat an invalid ticket and therefore I will close it. Thanks for reporting anyway.

**Comment by sualko** [comment]
If you like to fix it by your own, you probably have to remove the `'notnull' => true,` line for every `boolean` column in the following files.

https://github.com/sualko/cloud_bbb/blob/master/lib/Migration/Version000000Date20200416124731.php
https://github.com/sualko/cloud_bbb/blob/master/lib/Migration/Version000000Date20210419132000.php
https://github.com/sualko/cloud_bbb/blob/master/lib/Migration/Version000000Date20200617055735.php
https://github.com/sualko/cloud_bbb/blob/master/lib/Migration/Version000000Date20200829112301.php

**Comment by pasith3e** [comment]
Thanks for the Info.
Remove it does not work, I think the Default is true?
Changing the value to false works for me.
