### ISSUE TITLE
"Server error" after Upgrade to NC22

### ISSUE THREAD

**Issue by anschuetz** [sualko/cloud_bbb#167]
**Describe the bug**
After Upgrading to NC22 the plugin stops working. Instead of the rooms-overview there is only an exclamationmark and the text "server error" ("Serverfehler" in my case, german localisation)

**To Reproduce**
1. Go to BigBlueButton-App
2. See error

**Expected behavior**
My rooms should appear and it should be possible to make settings, start conferences,...

**Screenshots**
<img width="781" alt="bbb-plugin-error" src="https://user-images.githubusercontent.com/1607509/124937790-039e5380-e008-11eb-8feb-edae1706fddf.png">

**System (please complete the following information):**
 - Browser with version [e.g. chrome, safari]
 - App version [e.g. 0.1.0]
 - Nextcloud version [e.g. 18.0.1]
 - BigBlueButton version [e.g. 2.2.9]
 - Is your BigBlueButton instance working with Greenligh? yes/no
 - Did you enter your BBB API url and secret? yes/no

**Nextcloud log:**
{"reqId":"o5lMBPbaCVDc8tnFFudP","level":3,"time":"2021-07-08T15:19:02+01:00","remoteAddr":"***replacedForPrivacy***","user":"***replacedForPrivacy***","app":"index","method":"GET","url":"/apps/bbb/rooms","message":"Undefined class constant 'CIRCLES_ALL'","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36","version":"22.0.0.11","exception":{"Exception":"Exception","Message":"Undefined class constant 'CIRCLES_ALL'","Code":0,"Trace":[{"file":"/var/www/html/lib/private/AppFramework/App.php","line":156,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\BigBlueButton\\Controller\\RoomController"},"index"]},{"file":"/var/www/html/lib/private/Route/Router.php","line":301,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\BigBlueButton\\Controller\\RoomController","index",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"bbb.room.index"}]},{"file":"/var/www/html/lib/base.php","line":1000,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/bbb/rooms"]},{"file":"/var/www/html/index.php","line":36,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","Line":158,"Previous":{"Exception":"Error","Message":"Undefined class constant 'CIRCLES_ALL'","Code":0,"Trace":[{"file":"/var/www/html/custom_apps/bbb/lib/Controller/RoomController.php","line":62,"function":"getCircleIds","class":"OCA\\BigBlueButton\\CircleHelper","type":"->","args":["az"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":217,"function":"index","class":"OCA\\BigBlueButton\\Controller\\RoomController","type":"->","args":[]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":126,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\BigBlueButton\\Controller\\RoomController"},"index"]},{"file":"/var/www/html/lib/private/AppFramework/App.php","line":156,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\BigBlueButton\\Controller\\RoomController"},"index"]},{"file":"/var/www/html/lib/private/Route/Router.php","line":301,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\BigBlueButton\\Controller\\RoomController","index",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"bbb.room.index"}]},{"file":"/var/www/html/lib/base.php","line":1000,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/bbb/rooms"]},{"file":"/var/www/html/index.php","line":36,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/html/custom_apps/bbb/lib/CircleHelper.php","Line":39},"CustomMessage":"--"}}

**Javascript log:**
xhr.js:177 GET https://**replacedForPrivacy**/apps/bbb/rooms 500
(anonymous) @ xhr.js:177
e.exports @ xhr.js:13
e.exports @ dispatchRequest.js:50
Promise.then (async)
u.request @ Axios.js:61
r.forEach.u.<computed> @ Axios.js:76
(anonymous) @ bind.js:9
(anonymous) @ Api.ts:147
u @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
(anonymous) @ manager.js?v=736aa7d7-48:1
c @ manager.js?v=736aa7d7-48:1
value @ manager.js?v=736aa7d7-48:1
(anonymous) @ App.tsx:70
ol @ react-dom.production.min.js:211
bu @ react-dom.production.min.js:257
t.unstable_runWithPriority @ scheduler.production.min.js:19
Wo @ react-dom.production.min.js:122
hu @ react-dom.production.min.js:257
(anonymous) @ react-dom.production.min.js:256
B @ scheduler.production.min.js:17
C.port1.onmessage @ scheduler.production.min.js:14

**Additional context**
nothing else to be said :)

**Comment by anschuetz** [comment]
Ah... one more thing:
You CAN actually add new rooms, but all the already configurated rooms are gone and replaced with "ServerError"

**Comment by joergmschulz** [comment]
this app isn't ready for NC 22. see #164 and the related pull request.

**Comment by pasith3e** [comment]
Workaround: Disable the Circles app.

**Comment by anschuetz** [comment]
@pasith3e thank you! This workaround saves my Life!

**Comment by mhl66** [comment]
@pasith3e: sorry, this workaround did not work: circles was not enabled at all in my nextcloud 22 installation, alas, the server error persists.

**Comment by hmt** [comment]
works for me too. I have Contacts app installed too. Maybe that makes a difference?
