### ISSUE TITLE
Column "oc_bbb_rooms"."record" is type Bool and also NotNull, so it can not store "false"

### ISSUE THREAD

**Issue by seraphyn** [sualko/cloud_bbb#170]
**Describe the bug**
Tried to install BigBlueButton Integration1.4.2 via apps in Backend

**To Reproduce**
1. Go to apps
2. Search Big
3. Click download an activate
4. See error: Column "oc_bbb_rooms"."record" is type Bool and also NotNull, so it can not store "false".

**Expected behavior**
Installlation and use API-URL and key to start testing

**Screenshots**
![image](https://user-images.githubusercontent.com/140527/126124102-03058dcd-4797-4876-a582-f98224e6d282.png)

**System :**
 - firefox on Debian 78.12.0esr 64-Bit
 - App version 1.4.2
 - Nextcloud version 22.0

**Nextcloud log:**
[settings] Error: could not enable apps

POST /index.php/settings/apps/enable
from 172.31.253.236 by admin at 2021-07-19T07:50:41+00:00

**Additional context**
stay healthy

**Comment by sualko** [comment]
https://github.com/sualko/cloud_bbb/issues?q=is%3Aissue+22+is%3Aclosed

**Comment by seraphyn** [comment]
Close this please, saw : https://github.com/sualko/cloud_bbb/issues/169
