### ISSUE TITLE
Nextcloud 22 compatibility

### ISSUE THREAD

**Issue by mhl66** [sualko/cloud_bbb#171]
This is #169 re-opened as "feature request" = ardent attempt to appeal to sualko, who should be quite aware that this showstopper is open since the NC 22 release 2021-07-06.

Should be considered as friendly reminder and is not to be caustically closed again.

**Comment by joergmschulz** [comment]
don't waste your and the developer's time but try to test&resolve the remaining issues. The open PR will neither replace thorough tests nor resolve all the other open issues.
