### ISSUE TITLE
Avatar images not showing in BBB HTML5 client

### ISSUE THREAD

**Issue by fcovecino** [sualko/cloud_bbb#177]
**Describe the bug**
Instead of the user avatar (the nextcloud profile image) the BBB HTML client shows a broken image icon.

**To Reproduce**
1. Setup a profile image in Nextcloud 
2. Start a meeting room
3. Broken image icon shown instead of the avatar in the users list and chat of BBB

I see the link is right and loads on the browser (https://[host]/index.php/avatar/[user]/32 in my case) but for some reason in the browser debugger it returns a 404 error.

Tested it in firefox and edge. 

**Expected behavior**
The avatar image should be shown.

**Screenshots**
![image](https://user-images.githubusercontent.com/79067086/133356220-035e0f58-9dfe-49e0-8a20-bd5bfcfc0224.png)

**System (please complete the following information):**
 - Browser with version Firefox 92.0 64bit
 - App version 1.4.2
 - Nextcloud version 19.0.12
 - BigBlueButton version  2.3.13
 - Is your BigBlueButton instance working with Greenligh? no
 - Did you enter your BBB API url and secret? yes

**Nextcloud log:**

```
No
```

**Javascript log:**

```
32:1 GET https://[host]/index.php/avatar/[user]/32 404 (Not Found)
Image (async)
te @ 17e8e6c91a1aefa37d2b991249357ce7fb1a7cff.js?meteor_js_resource=true:69
ys @ 17e8e6c91a1aefa37d2b991249357ce7fb1a7cff.js?meteor_js_resource=true:69
Ul @ 17e8e6c91a1aefa37d2b991249357ce7fb1a7cff.js?meteor_js_resource=true:69
Wl @ 17e8e6c91a1aefa37d2b991249357ce7fb1a7cff.js?meteor_js_resource=true:69
Bl @ 17e8e6c91a1aefa37d2b991249357ce7fb1a7cff.js?meteor_js_resource=true:69
Al @ 17e8e6c91a1aefa37d2b991249357ce7fb1a7cff.js?meteor_js_resource=true:69
(anonymous) @ 17e8e6c91a1aefa37d2b991249357ce7fb1a7cff.js?meteor_js_resource=true:69
n.unstable_runWithPriority @ 17e8e6c91a1aefa37d2b991249357ce7fb1a7cff.js?meteor_js_resource=true:87
ui @ 17e8e6c91a1aefa37d2b991249357ce7fb1a7cff.js?meteor_js_resource=true:69
di @ 17e8e6c91a1aefa37d2b991249357ce7fb1a7cff.js?meteor_js_resource=true:69
pi @ 17e8e6c91a1aefa37d2b991249357ce7fb1a7cff.js?meteor_js_resource=true:69
Cl @ 17e8e6c91a1aefa37d2b991249357ce7fb1a7cff.js?meteor_js_resource=true:69
enqueueForceUpdate @ 17e8e6c91a1aefa37d2b991249357ce7fb1a7cff.js?meteor_js_resource=true:69
_.forceUpdate @ 17e8e6c91a1aefa37d2b991249357ce7fb1a7cff.js?meteor_js_resource=true:45
(anonymous) @ 17e8e6c91a1aefa37d2b991249357ce7fb1a7cff.js?meteor_js_resource=true:293
_compute @ 17e8e6c91a1aefa37d2b991249357ce7fb1a7cff.js?meteor_js_resource=true:255
_recompute @ 17e8e6c91a1aefa37d2b991249357ce7fb1a7cff.js?meteor_js_resource=true:255
o._runFlush @ 17e8e6c91a1aefa37d2b991249357ce7fb1a7cff.js?meteor_js_resource=true:255
a @ 17e8e6c91a1aefa37d2b991249357ce7fb1a7cff.js?meteor_js_resource=true:1
postMessage (async)
u @ 17e8e6c91a1aefa37d2b991249357ce7fb1a7cff.js?meteor_js_resource=true:1
_ @ 17e8e6c91a1aefa37d2b991249357ce7fb1a7cff.js?meteor_js_resource=true:255
invalidate @ 17e8e6c91a1aefa37d2b991249357ce7fb1a7cff.js?meteor_js_resource=true:255
changed @ 17e8e6c91a1aefa37d2b991249357ce7fb1a7cff.js?meteor_js_resource=true:255
(anonymous) @ 17e8e6c91a1aefa37d2b991249357ce7fb1a7cff.js?meteor_js_resource=true:271
(anonymous) @ 17e8e6c91a1aefa37d2b991249357ce7fb1a7cff.js?meteor_js_resource=true:271
_runAfterUpdateCallbacks @ 17e8e6c91a1aefa37d2b991249357ce7fb1a7cff.js?meteor_js_resource=true:271
_performWrites @ 17e8e6c91a1aefa37d2b991249357ce7fb1a7cff.js?meteor_js_resource=true:271
_flushBufferedWrites @ 17e8e6c91a1aefa37d2b991249357ce7fb1a7cff.js?meteor_js_resource=true:271
_livedata_data @ 17e8e6c91a1aefa37d2b991249357ce7fb1a7cff.js?meteor_js_resource=true:271
onMessage @ 17e8e6c91a1aefa37d2b991249357ce7fb1a7cff.js?meteor_js_resource=true:271
(anonymous) @ 17e8e6c91a1aefa37d2b991249357ce7fb1a7cff.js?meteor_js_resource=true:269
forEachCallback @ 17e8e6c91a1aefa37d2b991249357ce7fb1a7cff.js?meteor_js_resource=true:269
socket.onmessage @ 17e8e6c91a1aefa37d2b991249357ce7fb1a7cff.js?meteor_js_resource=true:269
r.dispatchEvent @ 17e8e6c91a1aefa37d2b991249357ce7fb1a7cff.js?meteor_js_resource=true:269
k._dispatchMessage @ 17e8e6c91a1aefa37d2b991249357ce7fb1a7cff.js?meteor_js_resource=true:269
k._didMessage @ 17e8e6c91a1aefa37d2b991249357ce7fb1a7cff.js?meteor_js_resource=true:269
o.ws.onmessage @ 17e8e6c91a1aefa37d2b991249357ce7fb1a7cff.js?meteor_js_resource=true:269
```

**Additional context**

**Comment by sualko** [comment]
> I see the link is right and loads on the browser, but for some reason in the browser debugger it returns a 404 error.

It could be a content security policy or cors issue, but that usually doesn't result in a 404.

Since the url seams to be right, I don't think this is related to my application.

**Comment by sualko** [comment]
If you like, you can send me some test credentials to your NC instance via klaus@jsxc.org.

**Comment by fcovecino** [comment]
Hello, 

To fix it the visibility of the profile picture needs to be set to Published... in my case, for some reason Private is the default.

![image](https://user-images.githubusercontent.com/79067086/140551840-2a4af429-9c54-41d1-a93d-e0e54219de44.png)

Do you have the same issue if you change your profile picture to Private?

**Comment by sualko** [comment]
Thanks for checking that. It's the same for me. I'm currently unsure how I should proceed, because if the user does not want to have his avatar published, we should probably respect that.

**Comment by sualko** [comment]
I did some tests and this issue only occurs with Nextcloud 19. Alll versions upwards will receive the uploaded avatar or the default one. Since NC 19 is end of life, I will not provide a fix for it.
