### ISSUE TITLE
[js-init] Erreur 1

### ISSUE THREAD

**Issue by guidtz** [sualko/cloud_bbb#18]
Hello,
   good initiative to create this apps in nextcloud. But I have somes errors when I try to build it 
```
php composer.phar install --no-dev -o
Loading composer repositories with package information
Installing dependencies from lock file
Package operations: 1 install, 0 updates, 0 removals
  - Installing bigbluebutton/bigbluebutton-api-php (dev-fork 7523099): Cloning 75230993ab from cache
Generating optimized autoload files
yarn install
ERROR: [Errno 2] No such file or directory: 'install'
Makefile:24 : la recette pour la cible « js-init » a échouée
make: *** [js-init] Erreur 1
```
I'll try it in debian9 
Regards

**Comment by sualko** [comment]
You need [yarn the package manager](https://yarnpkg.com), see https://stackoverflow.com/questions/46013544/yarn-install-command-error-no-such-file-or-directory-install

**Comment by guidtz** [comment]
yes It's works with a recent yarn version. Thanks
