### ISSUE TITLE
Error deleting recordings through scalelite

### ISSUE THREAD

**Issue by ferfebles** [sualko/cloud_bbb#182]
**Describe the bug**
While trying to delete a recording

**To Reproduce**
1. Go to the BBB button
2. Click on 'recordings'
3. Scroll down to one of the recordings
4. Click on the 'delete' button
5. Answer yes to the question "Are you sure you want to delete the recording from "25/10/2021, 11:33:02"? This operation cannot be undone."
6. You can see the error "Server error. Could not delete record"

**Expected behavior**
The recording to be deleted.

**Screenshots**

**System (please complete the following information):**
 - Browser with version: Vivaldi 4.3.2439.44
 - App version: 2.0.0
 - Nextcloud version: 22.2.0
 - BigBlueButton version: 2.3.8 (2397)
 - Is your BigBlueButton instance working with Greenligh? yes
 - Did you enter your BBB API url and secret? yes

**Nextcloud log:**

```
{"reqId":"s9h65uL1KyRhilUgfTBM","level":3,"time":"2021-10-25T12:05:21+01:00","remoteAddr":"172.17.255.10","user":"admincauce","app":"index","method":"DELETE","url":"/index.php/apps/bbb/server/record/8f9fd2ecb600de770f3ee7a01e48461ff22af75b-1635157982541","message":"Found no record with given id","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36","version":"22.2.0.2","exception":{"Exception":"Exception","Message":"Found no record with given id","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/bbb/lib/Controller/ServerController.php","line":66,"function":"getRecording","class":"OCA\\BigBlueButton\\BigBlueButton\\API","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":217,"function":"deleteRecord","class":"OCA\\BigBlueButton\\Controller\\ServerController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":126,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":156,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":301,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":1000,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/apps/bbb/lib/BigBlueButton/API.php","Line":197,"CustomMessage":"--"},"id":"61769376f008a"}
```

**Javascript log:**

```
RoomRow.tsx:143 Could not delete recording Error: Request failed with status code 500
    at e.exports (createError.js:16)
    at e.exports (settle.js:17)
    at XMLHttpRequest.p.onreadystatechange (xhr.js:62)
```

**Additional context**
Tested from Greenlight and from a Moodle extension. They can record and delete recordings. But from Nextcloud we got the error.

I saw the similar issue https://github.com/sualko/cloud_bbb/issues/76 and checked that the changes made at that moment are in the code of the BBB app v2.0.0 that we have installed.

**Comment by ferfebles** [comment]
Is there anything we could do to help diagnose this problem?

**Comment by sualko** [comment]
> Is there anything we could do to help diagnose this problem?

Would be great if you could provide the response from the recordings request for that room.
