### ISSUE TITLE
Use meta parameters to indentify the origin of a conference

### ISSUE THREAD

**Issue by kaystrobach** [sualko/cloud_bbb#184]
**Is your feature request related to a problem? Please describe.**

Wenn managing a big cluster it would be nice to identify the source of connections. Currently the plugin transfers no information.

**Describe the solution you'd like**

Greenlight sets it like this:

* https://github.com/bigbluebutton/greenlight/blob/master/app/controllers/concerns/bbb_server.rb#L71

The official API Client does it like this:

```
        $createMeetingParams = new CreateMeetingParameters($this->getIdentifier(), $this->getMeetingName());
        $createMeetingParams->addMeta('bbb-origin-version', '<version>');
        $createMeetingParams->addMeta('bbb-origin', 'Nextcloud');
        $createMeetingParams->addMeta('bbb-origin-server-name', $_SERVER['SERVER_NAME']);
```

With the library you are using it seems that you can use this method to append the needed data.

* https://github.com/littleredbutton/bigbluebutton-api-php/blob/master/src/Parameters/MetaParameters.php#L25

**Describe alternatives you've considered**

Monkey patching

**Additional context**

<img width="1692" alt="grafik" src="https://user-images.githubusercontent.com/1185776/143539285-3bfc9909-ea4b-45e9-9797-95baf0f32b3c.png">

**Sponsoring**

Sponsoring might by available - please contact me via Mail.

**Comment by sualko** [comment]
Thanks for your request. Sounds like a good idea which can be implemented easily.

> With the library you are using

It's just a better version than the original php api :wink:

Can you create a pr? The correct place would probably in https://github.com/sualko/cloud_bbb/blob/bdc054cd0935f303a4840a7b7b07eccb885f579e/lib/BigBlueButton/API.php#L152

You can get the app version from [IAppManager](https://github.com/nextcloud/server/blob/aee3bb42aeb716ff6c60401cd60ec7d6d7a36bec/lib/public/App/IAppManager.php#L60) and the server name from [IRequest](https://github.com/nextcloud/server/blob/aee3bb42aeb716ff6c60401cd60ec7d6d7a36bec/lib/public/IRequest.php#L313).

**Comment by kaystrobach** [comment]
Thanks a lot.
