### ISSUE TITLE
API URL is invalid

### ISSUE THREAD

**Issue by ranti71** [sualko/cloud_bbb#187]
**Describe the bug**
When adding bbb-API-URL, Error Message "API URL is invalid" is shown.
In Nextcloud error log, this entry is shown:
...
Verursacht durch BigBlueButton\Exceptions\NetworkException: Error during curl_exec. Error: Connection timed out after 10001 milliseconds
...
Nextcloud server is in a proxy environment without direct access to internet oder public dns servers.
Trying to connect api-url from console with curl or wget is working as expected, so server can connect to bbb-server.

**To Reproduce**
1. Go to 'Settings -> Administration -> Additional Settings'
2. Enter API-URL and Secret in  BigBlueButton settings
3. Save Settings
4. See error "API URL is invalid"

**Expected behavior**
Start Meeting in BBB from Nextcloud.

**Screenshots**
![image](https://user-images.githubusercontent.com/69325746/151355067-e3128543-adbc-4521-ac2b-2bb7cec7d492.png)

**System (please complete the following information):**
 - Chrome 97.0.4692.99
 - 2.2.0
 - Nextcloud version 23.0.1 RC3, same problem at 22.2.3
 - BigBlueButton version 2.3
 - Is your BigBlueButton instance working with Greenligh? yes
 - Did you enter your BBB API url and secret? yes

**Nextcloud log:**

```
REPLACE ME WITH YOUR NEXTCLOUD LOG
Verursacht durch BigBlueButton\Exceptions\NetworkException: Error during curl_exec. Error: Connection timed out after 10001 milliseconds

**Javascript log:**


REPLACE ME WITH YOUR JS LOG
<!-- Are there any errors or entries in your javascript console related to this app? You can open the console with CTRL+SHIFT+I -->
client.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'value')
    at Y._checkForDuplication (client.js:1:73880)
    at Y._checkFormForPassword (client.js:1:73943)
    at HTMLInputElement.t.submit.t.submit.addEventListener.passive (client.js:1:73228)
_checkForDuplication @ client.js:1
_checkFormForPassword @ client.js:1
t.submit.t.submit.addEventListener.passive @ client.js:1
main.js?v=77795537-27:1358 $ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.
ge @ main.js?v=77795537-27:1358
get @ main.js?v=77795537-27:1358
(anonymous) @ admin.js?v=77795537-27:1
dispatch @ main.js?v=77795537-27:25
g.handle @ main.js?v=77795537-27:25
client.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'value')
    at Y._checkForDuplication (client.js:1:73880)
    at Y._checkFormForPassword (client.js:1:73943)
    at HTMLFormElement.t.form.t.form.addEventListener.passive (client.js:1:73132)
_checkForDuplication @ client.js:1
_checkFormForPassword @ client.js:1
t.form.t.form.addEventListener.passive @ client.js:1
main.js?v=77795537-27:1358 $ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.
ge @ main.js?v=77795537-27:1358
get @ main.js?v=77795537-27:1358
e @ admin.js?v=77795537-27:1
(anonymous) @ admin.js?v=77795537-27:1
Promise.catch (async)
(anonymous) @ admin.js?v=77795537-27:1
dispatch @ main.js?v=77795537-27:25
g.handle @ main.js?v=77795537-27:25


**Additional context**

**Comment by sualko** [comment]
If you use Scalelight, please check the [troubleshooting guide](https://github.com/sualko/cloud_bbb#pick-troubleshooting).

> Nextcloud server is in a proxy environment without direct access to internet oder public dns servers.

In this case you have to make sure that php is reaching bbb. That's not related to this application, therefore I close this issue. If you need consulting for the configuration of php, please write me an email.
