### ISSUE TITLE
Manage recordings

### ISSUE THREAD

**Issue by guidtz** [sualko/cloud_bbb#19]
Hello,
  good jobs. It's a very good idea to integrate bbb with nextcloud. Do you plan to integrate records video in nextcloud ? There is for example a projet wich could set records in mp4 file and if we could integrate that in nextcloud it will be a good features for users to download videos. 

https://github.com/jibon57/bbb-recorder

Regards

**Comment by sualko** [comment]
I need only a specific set of features for my use case, so I will probably not implement this anytime soon. But maybe there is someone who want to do it (I'm happy to help), or is willing to pay me for that.

**Comment by sualko** [comment]
You have now the possibility to manage recordings similar to Greenlight, but it's not possible to get a single video file. The linked project is interesting, but cannot integrate this into a php application.

**Comment by guidtz** [comment]
Very very good job ...
