### ISSUE TITLE
Allow duplicating existing sessions

### ISSUE THREAD

**Issue by ruedigerkupper** [sualko/cloud_bbb#191]
We deploy Nextcloud with BBB-plugin at a public school. Teachers use BBB via NC for communicating to pupils and parents.
Often, our users need to create a new BBB session based on an old one (like duplicating the welcome text, but allowing different client users).
Please add an option for duplicating an existing BBB-Session in NC, but with a different public link.

**Comment by sualko** [comment]
That's a nice idea. Currently I'm busy with other stuff, so it can take some time to implement it. If you like to speed it up, please consider to get a sponsor for it. Just write me an email.

**Comment by ruedigerkupper** [comment]
👍 Thank you!
