### ISSUE TITLE
Please provide access option: send all users to lobby

### ISSUE THREAD

**Issue by ruedigerkupper** [sualko/cloud_bbb#192]
The BBB plugin provides different access modes, one being "internal + send guests to lobby". This still is a very permissive option, allowing access without manager confirmation for all users registered to the NC instance.
We are a public school deploying NC to all teachers and pupils. All of our users, teachers and pupils, are registered users of our NC instance. It is no option allowing all pupils to BBB without any confirmation.

Please, in your BBB plugin, provide the privacy option "send all users to lobby".

**Comment by sualko** [comment]
I see the point and think this is a good starter issue. So pull requests welcome :wink:

**Comment by ruedigerkupper** [comment]
Great, thank you!!
