### ISSUE TITLE
Documentation: does cloud_bbb stores all its setup in Nextcloud bases or directly in BBB

### ISSUE THREAD

**Issue by b3** [sualko/cloud_bbb#193]
I use cloud_bbb to access an instance of BBB. I would like to update this instance. A lot of rooms have been created by our users.

I would like to be sure that upgrading BBB will not lost all user's room.

I guess that all these room setup are stored directly in some Nextcloud database created by bbb_cloud. In other words as I am no expert at all nor in BBB, nor in Nextcloud, I would like to know if BBB stores some information on rooms where they are unused or not.

I just had a look at [BBB API](https://docs.bigbluebutton.org/dev/api.html#create) and I guess no information on rooms are stored inside BBB thus delegating this job to client (such as bbb_cloud or greenlight).

Am I right?

BTW, I am sorry to asked that here (as an issue even if it is not a bug report or feature request) but did not find a cleaner way to ask for such help. Do not hesitate to correct me if there is one.

**Comment by sualko** [comment]
> Am I right?

You are right. You can use whatever BBB server you like and the rooms will stay the same.

**Comment by b3** [comment]
Thank's a lot (for the answer and the nice work).
