### ISSUE TITLE
Add analytics Callback URL configuration parameter to allow statistics generation

### ISSUE THREAD

**Issue by pielonet** [sualko/cloud_bbb#194]
Hi,

Thank you for this great Nextcloud app.

I wish I had the possibility to enter the following configuration parameter for this extension: `meta_analytics-callback-url`

It takes the form of a URL and should be added to each BBB API room creation call query string. The whole metadata of the meeting gets posted to this URL after the meeting has ended.

It allows the generation of nice statistics concerning rooms and participants as used in this project : https://github.com/betagouv/bbb-analytics.

(It is a native possibility offered by BBB as referenced here : https://github.com/bigbluebutton/bigbluebutton/blob/7c355d627332c35b3cf8ec15bcc7d90a886f5dd4/record-and-playback/core/scripts/post_events/post_events_analytics_callback.rb#L151)

Kind regards,
Thierry

**Comment by sualko** [comment]
If you do not need any UI configuration for this, this should be easy to implement as app config (`occ config:app:set bbb KEY --value "VALUE"`).

**Comment by sualko** [comment]
> You're right, but the app code has to be modified

Yes, it's not working right out of the box, but my comment was just meant as a hint how this could be implemented. So PR welcome :wink:

**Comment by pielonet** [comment]
@sualko I created a PR #197  for this feature. Thanks for reviewing !
Kind regards,
Thierry
