### ISSUE TITLE
Add translation

### ISSUE THREAD

**Issue by sualko** [sualko/cloud_bbb#2]

**Comment by Ludovicis** [comment]
Hello,
How can i help you with french translation ? On Transifex ?

**Comment by sualko** [comment]
Thanks for the offer. I will ping you when everything is setup.

**Comment by jbonor** [comment]
Hi, I would like to help with the Spanish translation.

**Comment by sualko** [comment]
Thanks for the offer. I prepared everything and it should be ready to translate on transifex as soon as nextcloud/docker-ci#217 is merged. Thanks again for contributing.
