### ISSUE TITLE
Error warning many times per second kills NextCloud

### ISSUE THREAD

**Issue by UMenter** [sualko/cloud_bbb#205]
**Description of the bug**

BBB sends a warning to the NextCloud several times per second and makes it crash.

**To Reproduce**

In the moment the integration App is enabled, the warning massages floods the NextCloud and brings it to crash.

**Expected behavior**
No flooding warnings

**Screenshots**
no

**System (please complete the following information):**
 - all Browser 
 - App version BigBlueButton integration 2.2.0
 - Nextcloud version: Nextcloud Hub II (23.0.3)
 - BigBlueButton
 - Is your BigBlueButton instance working with Greenligh? yes
 - Did you enter your BBB API url and secret? No problem
 - Are you using a load balancer, like Scalelite? unknown

**Nextcloud log:**
Are there any errors in your Nextcloud log related to this app?  Yes

```
[bbb] Fehlersuche: /appinfo/app.php is deprecated, use \OCP\AppFramework\Bootstrap\IBootstrap on the application class instead.

GET /ocs/v2.php/search/providers?from=%2Fsettings%2Fapps
from 91.12.70.68 by admin at 2022-04-03T15:49:53+00:00
```

**Javascript log:**
no

**Additional context**
no

**Comment by sualko** [comment]
app.php is still required by some Nextcloud versions, so no way to remove that message. Just increase your log level at the moment.
