### ISSUE TITLE
Valid API URL rejected: “API URL is invalid”

### ISSUE THREAD

**Issue by bignose-debian** [sualko/cloud_bbb#208]
**Describe the bug**

When using an API URL for BigBlueButton (e.g. as provided by BBBOnDemand.com) the ‘cloud_bbb’ interface responds with “API URL is invalid”.

The URL is valid and should be accepted for use.

Using ‘cloud_bbb’ version 2.2.0.

**To Reproduce**

* Get the API URL and API Secret, from (e.g.) an account at bbbondemand.com.
** e.g. URL: `https://bbbondemand.com/api/v1/decafbaddecafbadbeef/bigbluebutton/api/`, secret: `dfouihh34o9utgbione095nioh6908o3`
* Log into NextCloud as an administrative user.
* Browse to ‘…/settings/admin/additional’.
* In the `bbb-api` form, enter the API URL and API Secret.
** The form shows an error “API URL is invalid” and will not use the API credentials.

The interface *does* accept a modified URL which is not the correct URL: it accepts `https://bbbondemand.com/api/v1/decafbaddecafbadbeef/bigbluebutton/`, but this is not the correct URL.

**Expected behavior**

The valid URL and Secret should be used as provided.

**Nextcloud log:**

I don't have direct access to the BigBlueButton server so cannot provide log entries.

**Comment by richp10** [comment]
I wonder if this is related to the note the readme Troubleshooting note with the following advice: 

`To connect to a ScaleLite server, use the url like https://yourscalelite.url/bigbluebutton/ without additional api/ and as secret ScaleLite's LOADBALANCER_SECRET`

This seems strange, the scalelite documentation say that it requires the url *including* the /api/ portion at the end: https://github.com/blindsidenetworks/scalelite#configure-your-front-end-to-use-scalelite

I cannot see anywhere in code that this plugin is changing the api url - but to my mind it should not.

**Comment by sualko** [comment]
> but this is not the correct URL.

It's the correct url, if it's working. The api postfix is added by the official php api.

**Comment by bignose-debian** [comment]
> I cannot see anywhere in code that this plugin is changing the api url - but to my mind it should not.

Yes, I agree with that; the URL should be used, as is.

> The api postfix is added by the official php api.

What does this mean? It sounds like the postfix is part of the correct URL in that case.
