### ISSUE TITLE
Nextcloud 24 compatibility

### ISSUE THREAD

**Issue by mokkin** [sualko/cloud_bbb#210]
Today NC 24 has been released and thousands of servers awaiting upgrades. In our case only the BBB integration has no valid upgrade candidate.

Therefore I ask you please to provide compatibility and increase max version number.

Thank you a lot for you great work so far!

**Comment by joergmschulz** [comment]
if fixed, pls tick here: https://help.nextcloud.com/t/any-apps-not-yet-compatible-with-24/136275

**Comment by mokkin** [comment]
For those who cannot wait: I tested the current version with a test instance on v24 and it still worked.

**Comment by joergmschulz** [comment]
so we can just add a PR here for the appinfo file?

**Comment by lortas** [comment]
Any progress here? I really like to update my Nextcloud to 24.x.x. But I do not want to loose my bbb integration. ;-)

**Comment by JojoBr0** [comment]
Is the "official" nc24 support coming any time soon?

**Comment by sualko** [comment]
It took a while, but the new version with support for Nextcloud 24 was released just seconds ago.
