### ISSUE TITLE
BBB 2.3.0 breaking Nextcloud 23

### ISSUE THREAD

**Issue by stable-it** [sualko/cloud_bbb#218]
**Describe the bug**
After the installation of the new version of BBB app, some menues show an internal server error page. Disabling the BBB app solves the problem.

**To Reproduce**
1. Go to 'Files Icon in the top bar' or 'Menu' -> 'Apps'
2. See error

**Expected behavior**
Expecting no server error

**Screenshots**
![Screenshot 2022-07-27 075137](https://user-images.githubusercontent.com/102606456/181171567-49528b18-9439-4b9a-bfba-164061023644.png)

**System (please complete the following information):**
 - Browser with version Firefox 102.0.1 (64-Bit)
 - App version 2.3.0
 - Nextcloud version 23.0.7
 - BigBlueButton version unknown
 - Is your BigBlueButton instance working with Greenligh? no
 - Did you enter your BBB API url and secret? yes
 - Are you using a load balancer, like Scalelite? no

**Nextcloud log:**
```
{"reqId":"iMdXRZlATfa6QoK5Uak3","level":3,"time":"July 23, 2021 08:10:48","remoteAddr":"255.255.255.255","user":"admin_customer","app":"settings","method":"POST","url":"/index.php/settings/apps/enable","message":"could not enable apps","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:90.0) Gecko/20100101 Firefox/90.0","version":"22.0.0.11","exception":{"Exception":"InvalidArgumentException","Message":"Column \"oc_bbb_rooms\".\"record\" is type Bool and also NotNull, so it can not store \"false\".","Code":0,"Trace":[{"file":"/var/www/customer/cloud.somecloud.de/lib/private/DB/MigrationService.php","line":461,"function":"ensureOracleConstraints","class":"OC\\DB\\MigrationService","type":"->","args":[{"__class__":"Doctrine\\DBAL\\Schema\\Schema"},{"__class__":"Doctrine\\DBAL\\Schema\\Schema"},3]},{"file":"/var/www/customer/cloud.somecloud.de/lib/private/DB/MigrationService.php","line":417,"function":"migrateSchemaOnly","class":"OC\\DB\\MigrationService","type":"->","args":["latest"]},{"file":"/var/www/customer/cloud.somecloud.de/lib/private/Installer.php","line":154,"function":"migrate","class":"OC\\DB\\MigrationService","type":"->","args":["latest",true]},{"file":"/var/www/customer/cloud.somecloud.de/apps/settings/lib/Controller/AppSettingsController.php","line":447,"function":"installApp","class":"OC\\Installer","type":"->","args":["bbb"]},{"file":"/var/www/customer/cloud.somecloud.de/lib/private/AppFramework/Http/Dispatcher.php","line":217,"function":"enableApps","class":"OCA\\Settings\\Controller\\AppSettingsController","type":"->","args":[["bbb"],[]]},{"file":"/var/www/customer/cloud.somecloud.de/lib/private/AppFramework/Http/Dispatcher.php","line":126,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Settings\\Controller\\AppSettingsController"},"enableApps"]},{"file":"/var/www/customer/cloud.somecloud.de/lib/private/AppFramework/App.php","line":156,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Settings\\Controller\\AppSettingsController"},"enableApps"]},{"file":"/var/www/customer/cloud.somecloud.de/lib/private/Route/Router.php","line":301,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Settings\\Controller\\AppSettingsController","enableApps",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"settings.AppSettings.enableApps"}]},{"file":"/var/www/customer/cloud.somecloud.de/lib/base.php","line":1000,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/settings/apps/enable"]},{"file":"/var/www/customer/cloud.somecloud.de/index.php","line":36,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/customer/cloud.somecloud.de/lib/private/DB/MigrationService.php","Line":595,"CustomMessage":"could not enable apps"}}
```

**Javascript log:**
```
No java script log
```

**Comment by busch1982** [comment]
I have a similar problem with the 
Update Nextcloud 24.02 to 24.03

updated to bbb App 2.3.0 in advance

Used Web Updater to update to Nextcloud version 24.03
`
TypeError: Symfony\Component\EventDispatcher\GenericEvent::getArgument(): Argument #1 ($key) must be of type string, int given, called in /var/www/nextcloud/lib/private/EventDispatcher/GenericEventWrapper.php on line 81 and defined in /var/www/nextcloud/apps/bbb/vendor/symfony/event-dispatcher/GenericEvent.php:60
Stack trace:
/var/www/nextcloud/lib/private/EventDispatcher/GenericEventWrapper.php(81): Symfony\Component\EventDispatcher\GenericEvent->getArgument()
/var/www/nextcloud/lib/private/Updater.php(499): OC\EventDispatcher\GenericEventWrapper->getArgument()
/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php(251): OC\Updater->OC\{closure}()
/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php(73): Symfony\Component\EventDispatcher\EventDispatcher->callListeners()
/var/www/nextcloud/lib/private/EventDispatcher/SymfonyAdapter.php(122): Symfony\Component\EventDispatcher\EventDispatcher->dispatch()
/var/www/nextcloud/lib/private/Repair.php(259): OC\EventDispatcher\SymfonyAdapter->dispatch()
/var/www/nextcloud/lib/private/Repair.php(122): OC\Repair->emit()
/var/www/nextcloud/lib/private/Updater.php(252): OC\Repair->run()
/var/www/nextcloud/lib/private/Updater.php(133): OC\Updater->doUpgrade()
/var/www/nextcloud/core/Command/Upgrade.php(235): OC\Updater->upgrade()
/var/www/nextcloud/apps/bbb/vendor/symfony/console/Command/Command.php(298): OC\Core\Command\Upgrade->execute()
/var/www/nextcloud/apps/bbb/vendor/symfony/console/Application.php(1024): Symfony\Component\Console\Command\Command->run()
/var/www/nextcloud/apps/bbb/vendor/symfony/console/Application.php(299): Symfony\Component\Console\Application->doRunCommand()
/var/www/nextcloud/apps/bbb/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
/var/www/nextcloud/lib/private/Console/Application.php(211): Symfony\Component\Console\Application->run()
/var/www/nextcloud/console.php(100): OC\Console\Application->run()
/var/www/nextcloud/occ(11): require_once('...')
`

Via the console you can fix the problem by disabling the bbb app

`sudo -u www-data php occ app:disable bbb`
`sudo -u www-data php occ upgrade`
`sudo -u www-data php occ maintenance:mode --off`
But I guess this happens with every update if you don't deactivate the bbb app first

**Comment by joergmschulz** [comment]
yes, this happens as well while upgrading from 23.current

**Comment by sualko** [comment]
Seams like two different errors. The first one probably happens, because Nextcloud added some checks for boolean columns. The second error occurs for me only on development builds. So maybe the build process broke, or @busch1982 is building it's own version from git. EDIT it seams the build process was faulty. 

Sorry for the inconvenience.
