### ISSUE TITLE
English words in French UI and I cannot find them in Transifex to translate them

### ISSUE THREAD

**Issue by Jerome-Herbinet** [sualko/cloud_bbb#222]
**Describe the bug**
Some words are displayed in English in our French UI.

**To Reproduce**
1. Go to BBB for Nextcloud in a French UI
2. See the English words (in yellow in the following screenshots)
![2022-09-02_16-43](https://user-images.githubusercontent.com/33763786/188174854-9cad471a-7592-41ea-ad67-49b77f234a7c.png)
![2022-09-02_16-42](https://user-images.githubusercontent.com/33763786/188174857-3e2b9b9f-ab0e-4f2b-a8f9-fd1839e2d255.png)

**Expected behavior**
Those words should be written in French.

**System (please complete the following information):**
 - Browser : Firefox 104
 - Nextcloud version 23.0.6
 - BigBlueButton version 2.4.8
 - Is your BigBlueButton instance working with Greenligh? No
 - Did you enter your BBB API url and secret? I don't know but maybe not necessary in this context. I can provide it later if necessary.
 - Are you using a load balancer, like Scalelite? I don't know but maybe not necessary in this context. I can provide it later if necessary.

**Nextcloud log:**

```
I can provide it later if necessary.
```

**Javascript log:**

```
I can provide it later if necessary.
```

**Comment by sualko** [comment]
From my side everything looks correct. I have no idea why the Nextcloud bot can't detect them. If I have some time, I will look into it.
