### ISSUE TITLE
Nextcloud 25 compatibility

### ISSUE THREAD

**Issue by mokkin** [sualko/cloud_bbb#223]
The same procedure as every release :wink: 
NC 25 will be released during the next days and thousands of servers awaiting upgrades. In our case only the BBB integration has no valid upgrade candidate.

Therefore I ask you please to provide compatibility and increase max version number.

Thank you again a lot for you great work so far!

**Comment by sualko** [comment]
You can help if you test the current version with NC 25 and report any issues back. That would be a time saver :+1:

**Comment by joergmschulz** [comment]
the beta release seems to work perfectly!

**Comment by sualko** [comment]
Just released. Thanks for testing.
