### ISSUE TITLE
unable to scroll in the list of rooms

### ISSUE THREAD

**Issue by JeremyCDP** [sualko/cloud_bbb#227]
**Describe the bug**
unable to scroll in the list of rooms

**To Reproduce**
1. Go to /apps/bbb/
2. Reduce the windows size (or have a lot of rooms created), till the window is small enough
3. try to scroll down

**Expected behavior**
Be able to scroll down
or have a scroll bar

**Screenshots**
![image](https://user-images.githubusercontent.com/56638395/201708494-d0cdb4c8-5913-4b7b-af47-405e9f32e79b.png)

**System (please complete the following information):**
 - problem is present in Brave [Version 1.45.118 Chromium: 107.0.5304.91 (Build officiel) (64 bits)](https://brave.com/latest/) as in Firefox 106.0.5 (64 bits)
 - App version : 2.4.0
 - Nextcloud version : 25.0.1
 - BigBlueButton version : BigBlueButton Server 2.4.9 (3087)
 - Is your BigBlueButton instance working with Greenligh? yes
 - Did you enter your BBB API url and secret? yes
 - Are you using a load balancer, like Scalelite? no

**Additional context**
worked fine with NextCloud 24

**Comment by battosai30** [comment]
+1 same here

**Comment by valentin-ed** [comment]
Same here !

**Comment by HurdmanBegins** [comment]
+1

**Comment by ferfebles** [comment]
Same here. Scroll not working after NC25 upgrade from NC24

**Comment by baumkirchner** [comment]
As a **workaround** until solved:
in `./apps/bbb/templates/manager.php` change **line 6** from
`    <div id="bbb-root" data-shortener="<?php p($_['shortener']); ?>"></div>`
to
`    <div id="bbb-root" style="display: block; height: 93vh; overflow: auto;" data-shortener="<?php p($_['shortener']); ?>"></div>`
Tested in _Nextcloud 25.0.3_ and _25.0.4_ / _cloud_bbb 2.4.0_ with _Firefox_ an _Chrome_
