### ISSUE TITLE
Failed to Save URL and API Key

### ISSUE THREAD

**Issue by sheyk87** [sualko/cloud_bbb#230]
When I try to configure the API URL and API Key, I click on Save, but it is not saved.

![Captura de pantalla de 2022-12-26 10-28-04](https://user-images.githubusercontent.com/86056803/209553930-e6dada1a-7113-4a9f-a705-68d4568e277e.png)

Apps Version: 
Plugin: BigBlueButton Integration, por Klaus Herberth licenciado bajo AGPL, 2.4.0-alpha
NextCloud: 24.0.6

**Comment by sheyk87** [comment]
Sorry, but the issue continue!

**Comment by sualko** [comment]
@sheyk87 it seams like you are the only one experience this issue and without further debug information, I can't do anything. Maybe you want to look at the expert configuration options: https://github.com/sualko/cloud_bbb#manual-configuration-for-experts

**Comment by sheyk87** [comment]
> @sheyk87 it seams like you are the only one experience this issue and without further debug information, I can't do anything. Maybe you want to look at the expert configuration options: https://github.com/sualko/cloud_bbb#manual-configuration-for-experts

I'll try! Thank You
