### ISSUE TITLE
Errors while installing integration

### ISSUE THREAD

**Issue by GuiLeme** [sualko/cloud_bbb#236]
**Describe the bug**

There are some minor issues when trying to install this in the Nextcloud server, I followed the instructions on https://github.com/sualko/cloud_bbb#rocket-install-it, and even with that, the `make build` didn't run as planed

So, firstly, I didn't have the `yarn` command, since I was configuring it in a plain Ubuntu 22.04 server, I only had `npm`, so I would like to ask if you guys are willing to change the default to `npm` or even, give the opportunity for the user to choose what they'd prefer.

Second point I would like to bring is to update Axios dependency for Nextcloud. So apparently, this old version of Axios is requesting a Node.js version of `^14.0.0`:
```log
yarn install
yarn install v1.22.19
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
error @nextcloud/axios@1.9.0: The engine "node" is incompatible with this module. Expected version "^14.0.0". Got "16.19.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
make: *** [Makefile:24: js-init] Error 1
```
And as you guys can see here https://github.com/sualko/cloud_bbb/blob/8a7de3ea03676fcb0748f05c2812ea097ca0f139/package.json#L40 This lib is in https://www.npmjs.com/package/@nextcloud/axios 2.3.0 and could be updated (cautiously, to not break anything, of course). By the way, it worked for me by just replacing `^1.3.2` for `^2.3.0`!

**Comment by sualko** [comment]
Using two package managers is not possible, so you have to install yarn, or use the pre build version. The second issue with the outdated package, will be fixed with the next upgrade.
