### ISSUE TITLE
Require Nextcloud account to join a room

### ISSUE THREAD

**Issue by sualko** [sualko/cloud_bbb#24]
Only people with a valid Nextcloud account should be able to join a room.

**Comment by atoav** [comment]
This should be an option if you ask me. At our university at least only staff has accounts, everybody else can enter a room if they know the right URL. So there are at least multiple scenarios I could imagine:
1. `Internal`: Only people with an nextcloud account should be allowed in
2. `Invite only`: Only people with knowledge of a key are allowed in (to allow for quick confidental meetings with people who don't have an account yet)
3. `Public`: Everyone with knowledge of the URL should be allowed in

These could be per-room settings (a bit like the existing record checkbox, but maybe a pull down menu). The `Public` setting would be the status quo.

**Comment by sualko** [comment]
There are even more possibilities, because BBB has a function, that a moderator has to approve every guest. We could also have a function were users are blocked until a moderator "arms" the room. This way someone could prepare the room before the first guest is joining. So many possibilities, but so short of time :wink:. It would be great if there would be some more developers joining. Maybe this could also be a school project.
