### ISSUE TITLE
Room access is restricted to certain users and groups

### ISSUE THREAD

**Issue by sualko** [sualko/cloud_bbb#25]
This is an enhancement to #24

**Comment by guidtz** [comment]
Hello, I think this is a major features for limit bbb rooms creation. After that I think bbb integration with nextcloud will be in production.

**Comment by sualko** [comment]
> limit bbb rooms creation

It depends on your definition of creation, because if you mean that you like to limit the ability to create rooms in Nextcloud, you can just enable the app for some groups.

This issue is about limiting access to rooms for certain user and groups.

**Comment by guidtz** [comment]
@sualko effectively !!! sorry :(

**Comment by variantolog** [comment]
In my opinion, the following algorithm of create and access to room would be ideal: 

1. A certain user (owner of room) create a room.
2. Allows access to the room to all (anonymous too) or Adds participants - certain users of Nextcloud. 3. In the case of a limited list of participants - owner click on the "Invite participants" button and Nextcloud sends to participants the emails with a link to this room.

**Comment by jacotec** [comment]
> It depends on your definition of creation, because if you mean that you like to limit the ability to create rooms in Nextcloud, you can just enable the app for some groups.

I'm looking for two hours now where this can be configured and I give up. I want to do this exact thing: Only members of a certain group should be able to use the app (and create and operate own rooms).

Where do I set this restriction?

**Comment by sualko** [comment]
> Where do I set this restriction?

It's an Nextcloud option, available for almost every app. You find it on the "app store" page.

![2020-06-19 08 14 38 wolke herberth eu 1c17727cd19e](https://user-images.githubusercontent.com/2974196/85102608-4d51ab80-b205-11ea-807b-2bb770c1d2a9.png)

**Comment by jacotec** [comment]
Thanks @sualko ... things can be so easy ;-)
