### ISSUE TITLE
Join as guest not working

### ISSUE THREAD

**Issue by remmedia** [sualko/cloud_bbb#27]
Join as Guest gives js error if klick send on enter display name.
Refused to send form data to 'bbb_url' because it violates the following Content Security Policy directive: "form-action 'self'".

**Comment by remmedia** [comment]
$policy->addAllowedFormActionDomain('DOMAIN'); needs to be addes

**Comment by sualko** [comment]
It's already be added, see:
https://github.com/sualko/cloud_bbb/blob/5f0d0bb77e719c0c2f70b5193cfcc6a96d3620ed/lib/Controller/JoinController.php#L105

Please fill the [issue template](https://github.com/sualko/cloud_bbb/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) and additionally provide the response header of the page where you have to enter your nickname.

**Comment by sualko** [comment]
I close this due to inactivity.
