### ISSUE TITLE
Entering Guest name when joining a confrence.

### ISSUE THREAD

**Issue by fanf1re** [sualko/cloud_bbb#28]
Minor update requested.  I fixed it in my local instance but when joining a conference by link the page that prompts to enter name says "How is your name?"  It should be "Please enter your name".  Willing to help but I have very limited programming skills.

**Comment by sualko** [comment]
Thanks for that correction. If you like you can make a pull request (request for a change) online, via https://github.com/sualko/cloud_bbb/blob/master/templates/publicdisplayname.php. You find a pen (edit icon) at the top bar, afterwards you just have to click through the dialog.

**Comment by sualko** [comment]
fixed via #29
