### ISSUE TITLE
What is this bigbluebutton integration for nextcloud ?

### ISSUE THREAD

**Issue by Ludovicis** [sualko/cloud_bbb#3]
Hello,
Can you tell us a little more about this app for nextcloud please? How it will look ...

**Comment by sualko** [comment]
Currently this app has the following functionality:

- Setup multiple rooms, with the following options
  - welcome message
  - max participants
  - recording
  - name
- Join room with NC displayname (if signed in)
- Custom displayname (if not signed in)
- Room owner is moderator
- Start presentation from file browser with custom presentation

There is still a lot missing compared to Greenlight, but it should be easily extendable. If you have time I would appreciate any pr.

![2020-04-27 10 23 00 dd8aed34a833](https://user-images.githubusercontent.com/2974196/80350835-9888b700-8871-11ea-8f3f-5bf6b9101aa5.png)
![2020-04-27 10 25 08 ab1eb935e199](https://user-images.githubusercontent.com/2974196/80350847-9a527a80-8871-11ea-922c-9d7f42f38afc.png)
![2020-04-27 10 26 21 0e3db5fee5d9](https://user-images.githubusercontent.com/2974196/80350853-9c1c3e00-8871-11ea-8e72-246bd05edf43.png)
