### ISSUE TITLE
error when start a room 

### ISSUE THREAD

**Issue by Walid-NX** [sualko/cloud_bbb#30]
Hi,

 I'm installed BBB app v 0.1.2 in Nexcloud v18 
 i successfully create a room but when i start it , a new tab is open with error 
and this is what i have in Nextcloud logs :

=========================================
Exception: String could not be parsed as XML
/var/www/html/nextcloud/apps/bbb/vendor/bigbluebutton/bigbluebutton-api-php/src/BigBlueButton.php - line 494:

SimpleXMLElement->__construct("<!DOCTYPE h … n")

/var/www/html/nextcloud/apps/bbb/vendor/bigbluebutton/bigbluebutton-api-php/src/BigBlueButton.php - line 112:

BigBlueButton\BigBlueButton->processXmlResponse(“api/create? … 6”, “”)

/var/www/html/nextcloud/apps/bbb/lib/Controller/JoinController.php - line 143:

BigBlueButton\BigBlueButton->createMeeting(BigBlueButto … {})

/var/www/html/nextcloud/apps/bbb/lib/Controller/JoinController.php - line 110:

OCA\BigBlueButton\Controller\JoinController->processPublicJoin(OCA\BigBlueB … 5}, “AdminCloud”, “welcloud”, null, null)

/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 170:

OCA\BigBlueButton\Controller\JoinController->index(“AdminCloud”, null, null)

/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 99:

OC\AppFramework\Http\Dispatcher->executeController(OCA\BigBlueB … {}, “index”)

/var/www/html/nextcloud/lib/private/AppFramework/App.php - line 125:

OC\AppFramework\Http\Dispatcher->dispatch(OCA\BigBlueB … {}, “index”)

/var/www/html/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47:

OC\AppFramework\App::main(“OCA\BigBlu … r”, “index”, OC\AppFramew … {}, { token: "x8 … "})

<>

OC\AppFramework\Routing\RouteActionHandler->__invoke({ token: "x8 … "})

/var/www/html/nextcloud/lib/private/Route/Router.php - line 299:

call_user_func(OC\AppFramew … {}, { token: "x8 … "})

/var/www/html/nextcloud/lib/base.php - line 1008:

OC\Route\Router->match("/apps/bbb/b/x8FNRmBCjxBeTMZL")

/var/www/html/nextcloud/index.php - line 38:

OC::handleRequest()

=========================================

In my browser, the  debugger show those errors :  

================================
![image](https://user-images.githubusercontent.com/65458835/82124747-e883db00-9798-11ea-89dc-710b64bf130c.png)

================================

any help please ?

**Comment by atoav** [comment]
I had a similar problem but could resolve it. Make sure:
- Your URL points to the bbb-api endpoint (this is usually `https:/bbb.your-url.com/bigbluebutton/`)
- Make sure to add a trailing slash (so `https:/bbb.your-url.com/bigbluebutton/` and not `https:/bbb.your-url.com/bigbluebutton`), otherwise it will crash

**Comment by sualko** [comment]
I would guess the same as @atoav. Please reopen if the error persist.

**Comment by Walid-NX** [comment]
Thanks a lot
but please condsider please consider that i'm a newbe with this, so could you tell me which file sould i edit to make those configurations ?

 I have my nextcloud serveur something like that : https://mynetxcloud.com where apache is configured for https://mynetxcloud.com , and my bbb is an app  included in mynextcloud 
should i cread a new apache vhost for BBB or there is other ways to do it ?

**Comment by atoav** [comment]
No need to edit a file: The configurations I mentioned are all done in the Nextcloud Admin settings of Nextcloud itself under the Tab `Additional Settings`.

You need to have the valid url and secret of a running bbb-instance however (run `bbb-conf --secret` on the machine where you installed bbb). Whether you have it running on the same box or not isn't really relevant (and shouldn't negatively impact performance).

I don't know too much about Apache (more familiar with Nginx), but you seem to propose to run BBB behind Apache configured as a reverse proxy — which is the recommended way of doing things (so Apache takes incomming Http traffic on ports 80 and 443 and passes it to the bbb running on your server at some other port). So I don't see why that wouldn't work. The biggest challenge would probably be to get the bbb-instance installed and configured properly.

**Comment by sualko** [comment]
>  my bbb is an app included in mynextcloud

I think you missed, that this app requires an external instance of BigBlueButton. It's just a client.

**Comment by Walid-NX** [comment]
Thanks a lot, know i see where is my problem
