### ISSUE TITLE
UX-Change: Move Room settings to start page

### ISSUE THREAD

**Issue by atoav** [sualko/cloud_bbb#31]
**Is your feature request related to a problem? Please describe.**
Currently the rooms are listed in the user settings. While this works, this seems like a unintuitive place for regular users, as they can't see it from their startpage.

**Describe the solution you'd like**
Ideally the settings for each users room would show up as an App like Notes, Deck, Files etc. This would also give the Addon more space for future expansion as the sidebar could be used.

Drafty mockup:
![bbbrooms](https://user-images.githubusercontent.com/6620266/82181062-13c61180-98e2-11ea-8832-382c500d42b6.jpg)  
(I didn't draw the content of the rooms pane, ignore please)

**Comment by sualko** [comment]
In my opinion this can be considered if we have more features, like e.g. an own playback player, but currently we have just some room configuration which in my view fits best in the settings section. It's similar to other apps, like Flow, Group folders and so on. Also my guess would be that only a small amount of users are generating there own rooms and for the remaining users it would clutter the app bar. Other thoughts?

**Comment by atoav** [comment]
> In my opinion this can be considered if we have more features

Sounds good.

I am speaking from the perspective of someone who gives BBB-related support for a University, at least here we have the experience that there is no real and simple solution that helps to keep presentation and files together. We currently use Greenlight, works well for managing users and rooms, okay for recordings and not at all for files. Of course we could setup Moodle, but Moddle is a complex beast and overkill.

I think a Nextcloud-based solution (as a frontend to bbb-web) could've the potential to make it easy to keep rooms, recordings and the files used in such a recording tied together, as well as allowing users to say download the used files or look at the recordings for a given room.

As for recording archival we are still looking for a good solution. I don't really believe the popcorn.js-based playback bbb currently uses is an answer that looks like it guarantuees long term readability. Of course there is the node/chrome based [bbb-recorder](https://github.com/jibon57/bbb-recorder), but I am not to sure about installing chrome on our servers (RAM hog).

**Comment by sualko** [comment]
> I think a Nextcloud-based solution (as a frontend to bbb-web) could've the potential to make it easy to keep rooms, recordings and the files used in such a recording tied together

Maybe https://github.com/ramezrafla/spreed-bigbluebutton is interesting for you, because it can take some time until we have a deep integration.

> As for recording archival we are still looking for a good solution.

See #32

> Of course there is the node/chrome based bbb-recorder, but I am not to sure about installing chrome on our servers (RAM hog).

I also would not install such a thing on my server, but https://github.com/createwebinar/bbb-download looks promising. (not sure if it's still maintained)

**Comment by joergmschulz** [comment]
spreed-bigbluebutton from ramezrafla seems to stop development not that the talk backend has been made open source (https://help.nextcloud.com/t/nextcloud-app-for-bigbluebutton-integration/74910/107).
It even seems to be more efficient than BBB itself. So, THIS app is the only useable integration for the time being.
