### ISSUE TITLE
Shared rooms

### ISSUE THREAD

**Issue by the-matzup** [sualko/cloud_bbb#33]
Up to now, rooms have been created by individual users, who are then also the sole moderators. 

We would like to share created rooms with a nextcloud group, who can all start the room as moderators.

My suggestion: 
Copy the room creation to the admin level as well and enable group sharing there. 
 
To understand our scenario:
We use BBB as a school. Each class has a BBB room where the participation link never changes. This makes it easy even for little students. Every teacher in the class can start the classroom session and is a moderator.
With the previous solution of the BBB app in NC this is not transferable. Here the students would need too many links to participate. A class has about 13 different teachers who then hand out 13 different links.

**Comment by sualko** [comment]
I think there are two kinds of shared rooms:

- Admin shares. Similar to the shared folder app. Rooms are shared on a global level.
- User shares. Similar to normal file shares. Everyone can share rooms with groups or users.

**Comment by sualko** [comment]
@the-matzup with dc30ec0 you can now define users/groups as moderators, but please beware that the room will not occur in there list of rooms.
