### ISSUE TITLE
createTime parameter submitted mismatches

### ISSUE THREAD

**Issue by afalce** [sualko/cloud_bbb#34]
**Describe the bug**
When creating a room from nextcloud, the registred createTime is different than BBB server createTime for room. The link to join the room is failing. If I generate the same link without createTime GET parameter, I succes the join.
**To Reproduce**
1. Go to nextcloud parameters and go to BigBlueButton menu
2. Change "Room Name with whatever name you want", and click "Create" button
3. Click the |> play button
4. See the "× Error: The createTime parameter submitted mismatches with the current meeting." error

**Expected behavior**
Once clicking play button, see the room

**System (please complete the following information):**
 - Mozilla Firefox 68.8.0esr
 - cloud_bbb 0.2.0
 - Nextcloud 18 ( tested with 17 )
 - BigBlueButton 2.2.0
 - Is your BigBlueButton instance working with Greenligh? no
 - Did you enter your BBB API url and secret? yes

**Logs**
I found nothing special on javascript console log or nextcloud logs.

**Additional context**
I Use Europe/Paris Timezone, but i don't think it changes anything. Seeing the Firefox "network console" : `&createTime=2147483647` parameter. Using api-mate to list available meetings show : `<createTime>1589813893299</createTime>`

**Comment by sualko** [comment]
Are you changing the name of an existing, already started room? Or does this error occur for new rooms?

**Comment by sualko** [comment]
Are you on a 32bit system?

**Comment by afalce** [comment]
Hi, thanks for fast answer, It happen at the creation of the room, you may got it, Nextcloud is on a armv7l build of linux.
I didn't  thought that it can changes  something

**Comment by sualko** [comment]
> I didn't thought that it can changes something

It's an int overflow, because bbb is using microseconds. Will be fixed in the next release. Sorry for your trouble.

**Comment by afalce** [comment]
it's ok, thanks you very much for your work !
