### ISSUE TITLE
I can no more add file to presentation between 0.1.2 and 0.2 version

### ISSUE THREAD

**Issue by Ludovicis** [sualko/cloud_bbb#39]
Hello,

After test, I can no more add file to presentation between 0.1.2 and 0.2 version of bbb application with Custom presentation Start a room with a selected presentation from your file browser.

My presentation is no more display in the room with 0.2 version.

I don't know if this log can help
"app":"PHP","method":"GET","url":"/apps/metadata/get?source=%2F.TEST_bbb3.png","message":"Unparenthesized `a ? b : c ? d : e` is deprecated. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)` at /var/www/html/nextcloud/apps/metadata/lib/Service/MetadataService.php#334",

I am on Nextcloud 19RC3

**Comment by sualko** [comment]
Bug reports which dismiss the template, will be close immediately. Please fill the template and reopen.

> I don't know if this log can help

No, because it's from the metadata app.
