### ISSUE TITLE
Disable recording

### ISSUE THREAD

**Issue by bpcurse** [sualko/cloud_bbb#40]
**Is your feature request related to a problem? Please describe.**
For privacy reasons it might not be desired to let Nextcloud users activate recording.
(I am aware that it can be disabled globally in the BigBlueButton Server settings)

**Describe the solution you'd like**
A simple checkbox in the main settings next to the API credentials that deactivates recording for all users when BigBlueButton rooms are created from the cloud.
If this is checked, either don't show record/recordings in user settings or gray out the recording option.

**Describe alternatives you've considered**
Allow/disallow recording only for a selectable user group.

Thank you very much for this app! It makes interacting with BigBlueButton a lot easier. Great job :+1:

**Comment by sualko** [comment]
I think if you generalize this request, it's about a default configuration.

> Thank you very much for this app! It makes interacting with BigBlueButton a lot easier. Great job +1

Thank you for the kind words. I'm happy that you like this app.

**Comment by sualko** [comment]
I close this in favor of the more general #43.
