### ISSUE TITLE
Admin settings to limit user options

### ISSUE THREAD

**Issue by digitalrevisor** [sualko/cloud_bbb#43]
**Is your feature request related to a problem? Please describe.**
On our Nextcloud instance we would like to limit what options our users have. For example we might not want all users to be able to use recordings, have unlimited rooms or to have unlimited participants in their rooms.

**Describe the solution you'd like**
As part of an admin settings page (or the existing admin settings on the additional settings page) it would be great to have these options:
1. Disable recordings for rooms.
2. Set max number of rooms for each user.
3. Set maximum limit for "max participant in room" for all rooms.

Additionally it would be even better to be able to decide what groups to apply these restrictions to, or to select groups not to apply the restrictions to. Not sure what the best solution would be for this but it would allow more flexibility. 

E.g most nextcloud users can only create a single room with no recording and max 4 participants, users in moderator group could create max 5 rooms with 100 participants and recordings, and users in admin group could create unlimited rooms with unlimited participants and recording.

Limiting by group would be useful for reducing pressure on BBB server and for those who have different user tiers on their nextcloud server.

**Describe alternatives you've considered**
I was looking at doing this just for our own server by hiding the columns entirely, but realized it would be better to have the option to do this from the admin settings.

**Additional context**
These are all functions that would be useful for our own usage. I would personally say that being able to disable recordings for users is the most useful, followed by being able to limit their number of participants and rooms. Limiting only to groups would also be very useful but I can imagine that being a much harder feature to implement.

**Comment by jacotec** [comment]
These are good ideas! I'd add this to the list:

- Ability to limit the use of the BBB integration in General to certain user groups

- Also the room type should be able to be limited by the admin, i.e. force the room type to "Internal + Waiting room for guests" so no user on your instance can create a "world open room".

**Comment by remmedia** [comment]
It also would be nice to have an option to limit room creation at all. that way it would be possible to have rooms in the list that were created by an administrator (or whatever) you just can join (as normal user [internal or internal+limited])
Another issu is, that as Admin it would be nice to see a list off all rooms created.

**Comment by sualko** [comment]
> It also would be nice to have an option to limit room creation at all

Just enable the app only for certain groups (app store) and share the room access url as url file.

> Another issu is, that as Admin it would be nice to see a list off all rooms created.

I'm reserved for such an option for privacy concerns, because not every NC admin is also an server administrator which is able to the db anyway, but it would be nice to have some kind of statistics.

**Comment by garblixa** [comment]
Please also add an option to select groups/users which are allowed to create meeting rooms.
In a school only a teacher should be able to create a room

Many thanks!
Klaus
