### ISSUE TITLE
Feedback version 0.4.0

### ISSUE THREAD

**Issue by spreeni151** [sualko/cloud_bbb#48]
I just tested 0.40 version of the app and want to give feedback. It's a very good idea to concentrate options in a seperate overlay windows, this keeps the list clean and clear. 

However there are some points that could be changed. 
1: The options window is not responsive. On smaller devices like notebooks or tablets the close-button at the top is covered by the headline of the nextcloud window. So it is not possible to close the options window. 

2: Some options are listed twice, like 'max people' and 'record'. This may confuse people. 

My recommendation would be: 'Max people' should be taken out of the list and only into the options, the 'allow recording' box should be taken out of the options-window and only into the list. This makes sense because it is such an important option which should be visible at first sight; it seems to be logical to place it near the recordings column.

Anyway, great work and many thanks to Bundesjugendring for sponsoring the development!

Frank

**Comment by sualko** [comment]
> I just tested 0.40 version of the app and want to give feedback

Awesome :clap: 

> The options window is not responsive.

I already discovered that and it will be fixed in the next release. Thanks for reporting anyway.

> Some options are listed twice, like 'max people' and 'record'. This may confuse people.

Maybe. Maybe not. For me it's a shortcut and I think it's no major issue.

> Anyway, great work

Thanks a lot.
