### ISSUE TITLE
Integrate uploading of a PDF presentation into the sidebar (under Sharing) instead of context menu

### ISSUE THREAD

**Issue by lars-becker** [sualko/cloud_bbb#5]
A suggestion for usability: since uploading a PDF is a one time event, it should be integrated into the sidebar instead of the context menu. A few configured rooms make the context menu, which is used quite regularly by some, a bit to clustered.

**Comment by sualko** [comment]
Why is this a one time event? After the room is closed the presentation will be gone.

But sure the workflow could be enhanced. For example it makes probably more sense to open a dialog with a list of rooms and check if the room is running, because in this case the document will not be used (bbb limitation).

**Comment by lars-becker** [comment]
I meant it's one time event for one particular event. I guess it really depends on workflows. We don't use BBB much for internal discussions in teams, but for trainings (we do political education). Those do not happen on a daily basis, whereas some members use the file app and most functions in it on a daily basis. E.g. when some users preconfigure three rooms, they have three additional entries, which they don't use for some days until they use it.  But I guess you're right. In organisations where BBB is used more spontaneously the workflow would be much different, of course. 

But still I have the feeling that even then the sharing sidebar would make sense to help users to remember/find the function. It some kind of sharing after all. Thanks for your great work! It already helps us a lot, since we have some older and more non-technical users who had troubles remembering the greenlight account data etc. :)

**Comment by lars-becker** [comment]
@sualko I made a screenshot to illustrate the problem with the current approach. If you want to delete a file you have to scroll down quite a lot, if you don't have a big screen.

![image](https://user-images.githubusercontent.com/8607154/151037931-a220bc82-6ebf-4574-a919-562bae379b2a.png)

**Comment by sualko** [comment]
I unterstand your problem, but currently I have no time to fix it. But there are good news: we are working with BigBlueButton on a new function which will require a redesign of the context menu. As result there will be a fix in the foreseeable future.
