### ISSUE TITLE
Setup behind proxy server

### ISSUE THREAD

**Issue by xdasde** [sualko/cloud_bbb#51]
is there any way to use this nextcloud app behind proxy server (for example squid) in not transperent setup. I had set proxy settings in config.php and also system envierment, but the bbb app still want to access the api adress directly? thanks for your help. I use version 0.5.1

**Comment by sualko** [comment]
It's not clear what you try to archive, but I guess it's just an configuration issue. Please try to be more precise.

**Comment by joergmschulz** [comment]
depends .... if your BBB is behind a proxy, you'll have issues if the WSS isn't forwarded correctly.

**Comment by xdasde** [comment]
The bbb server is external. The nextcloud server is behind proxy. tcpdump shows all internet traffic of this webserver goes through this proxy only the connection of this app will go directly to port 443 of our bbb server.

**Comment by sualko** [comment]
The app has to make request to the bbb api, so if you like to proxy those requests too, create a proxy for your bbb api and change the api url.
