### ISSUE TITLE
No meeting access for users not in restricted groups

### ISSUE THREAD

**Issue by GerdSc** [sualko/cloud_bbb#53]
**Describe the bug**
In my Nextcloud, BigBlueButton Integration is restricted to members of a special group (called "bbb"). Only group members are allowed to create or modify meetings ("rooms"). That's Ok. 
The Bug: A user, not member of "bbb"-group and logged in to nextcloud, can not participate in any meeting. If he loggs out of nextcloud, meeting participation works.

**To Reproduce**
1. add a group "bbb": nextcloud/settings/user; let a user ("bbbuser") become a member of this group
2. restrict acces to BigBlueButton: nextcloud/settings/apps/installed/bbb; right panel "restrict to groups" bbb (see screenshot)
3. log in to nextcloud as the "bbbuser", create a bbb-meeting (nextcloud/user/bbb), copy meeting-url
4. log out from nextcloud, go to the meeting by pasting the copied url: you are requested for your name - do nothing
5. log in to nextcloud as a user not member of group "bbb"
6. in a second browser tab or browser window, paste the meeting url - you are now not in the meeting, you are at your nextcloud startpage!

**Expected behavior**
Every user should have access to a meeting, independently from the login state to nextcloud!

**Screenshots**
![image](https://user-images.githubusercontent.com/46597933/86124141-e96b9480-bada-11ea-946a-5ceb93131d95.png)

**System (please complete the following information):**
 - Browser with version firefox 68.7.0esr, chromium  81.0.4044.92 
 - App version 0.5.1
 - Nextcloud version 18.0.6
 - BigBlueButton version: bbb-conf --version: bigbluebutton 1:2.2.0-5
 - Is your BigBlueButton instance working with Greenligh? no
 - Did you enter your BBB API url and secret? yes

**Nextcloud log:**

no error rel

**Javascript log:**

**Comment by sualko** [comment]
I guess there is nothing we can do here, because Nextcloud probably disables apps pretty early in the code, but I'm not sure. If I have time I will look into this.

**Comment by GerdSc** [comment]
Maybe it's easier to provide the same (restrict room creation to group members) within the admins settings page and handle it at room creation? 
The reason is: I dont want to allow all 500 nextcloud users to start a bbb meeting, because in the bbb documentation I've seen that the bbb server can handle only about 150 connections simultaneously.

**Comment by sualko** [comment]
> Maybe it's easier to provide the same (restrict room creation to group members) within the admins settings page and handle it at room creation?

I think this is the only possibility. If you have time, a pr would be appreciated.

**Comment by sualko** [comment]
@GerdSc if you have time it would be great if you could test #67.
