### ISSUE TITLE
Error on link creation

### ISSUE THREAD

**Issue by remmedia** [sualko/cloud_bbb#54]
**Describe the bug**
Error on link creation

**To Reproduce**
1. Go to 'a created room'
2. Click on 'create link'
4. See error: "Die URL zum Raum konnte nicht gespeichert werden." Url to room could not be saved

**Expected behavior**
it is working

**System (please complete the following information):**
 - Browser with version [ie on chrome/chrome newest version]
 - App version [e.g. 0.5.1]
 - Nextcloud version [e.g. 18.0.6]
 - BigBlueButton version [not relevant as copy link is working]
 - Is your BigBlueButton instance working with Greenligh? no
 - Did you enter your BBB API url and secret? yes

**Nextcloud log:**

```
NO ERROR LOG
```

**Javascript log:**

```
REPLACE ME WITH YOUR JS LOG
```

**Additional context**

**Comment by joergmschulz** [comment]
did you install https://apps.nextcloud.com/apps/files_linkeditor (Link Editor)?

**Comment by remmedia** [comment]
yes
the problem it not to open the link, but to create it
in version < 0.5.1 all worked fine

**Comment by sualko** [comment]
Please provide the javascript log and look for interesting requests in your network tab.
