### ISSUE TITLE
URL to room could not be stored

### ISSUE THREAD

**Issue by githubitm** [sualko/cloud_bbb#59]
**Describe the bug**
If I click on the Chain Symbol next to the name of the room to choose a Folder.
By clicking on "Choose" I get the Error Message "URL to room could not be stored."

**To Reproduce**
1. Go to Settings
2. Select "BigBlueButton" on the Left side.
3. Create a new room by entering the name of the room an click on "create"
4. Click on the Chain Symbol, choose a Folder an click on "Choose"
5. The Error Message "URL to room could not be stored." is shown.

**Expected behavior**

**Screenshots**

**System (please complete the following information):**
 - Browser with version Firefox 79.0
 - App version 0.5.1
 - Nextcloud version 18.0.6
 - BigBlueButton version 2.2.21
 - Is your BigBlueButton instance working with Greenligh? yes
 - Did you enter your BBB API url and secret? yes

![0_Screenshot_PluginSelection](https://user-images.githubusercontent.com/19891706/89619533-6504f200-d88e-11ea-8a10-91cf38314732.png)
![1_Screenshot_room](https://user-images.githubusercontent.com/19891706/89619532-646c5b80-d88e-11ea-9f35-34f6a46e9e88.png)
![2_Screenshot_Select-target-folder](https://user-images.githubusercontent.com/19891706/89619536-659d8880-d88e-11ea-86e9-721d3d325fb3.png)
![3_Screenshot_Error](https://user-images.githubusercontent.com/19891706/89619534-659d8880-d88e-11ea-95ee-d4bce3e7a1fa.png)

**Javascript log:**
Could not store room Error: Request failed with status code 404
    exports createError.js:16
    exports settle.js:17
    onreadystatechange xhr.js:61
    exports xhr.js:36
    exports xhr.js:12
    exports dispatchRequest.js:52
    promise callback*l.prototype.request Axios.js:61
    e Axios.js:86
    exports bind.js:9
    n Api.ts:131
    u runtime.js:45
    _invoke runtime.js:271
    t runtime.js:97
    c manager.js:1
    c manager.js:1
    value manager.js:1
    onClick RoomRow.tsx:82
    _ dialogs.js:426
    click dialogs.js:432
    jQuery 17
        _setOption
        dispatch
        handle
        add
        add
        on
        each
        each
        on
        t
        _setOption
        each
        _setOption
        i/e.widget/</a[t]</<
        _setOptions
        _setOptions
        i/e.widget/</a[t]</<

**Comment by sualko** [comment]
Thanks for this nice bug report. I'm not able to reproduce your error. Can you provide more details about the request which is resulting in a 404? Which room name do you use? Do you see any related messages in your Nextcloud log?

**Comment by sualko** [comment]
ping

**Comment by sualko** [comment]
I close this issue due to inactivity.

**Comment by baltaner** [comment]
Hello,
same problem here!
I am running 2 nextcloud instances - one with ldap-auth, the other with nextcloud database users.
The problem ONLY occurs in the instance with ldap-auth.
Any ideas?

**Comment by sualko** [comment]
@baltaner please open an new issue and fill the template.
