### ISSUE TITLE
bbb not showing up in menues

### ISSUE THREAD

**Issue by joergmschulz** [sualko/cloud_bbb#6]
BBB menu item is not showing up in menues in 18.0.3 regardless whether I disabled/enabled the previous spreed app.
Browser cache cleared, restarted web server. Nothing to be seen in nextcloud log file.

Don't know whether this message in the browser console is relevant: 
`failed to load resource: the server responded with a status of 404 `
<img width="522" alt="grafik" src="https://user-images.githubusercontent.com/6523646/80374730-6db15980-8897-11ea-99f1-be9cebd87c4e.png">

**Comment by joergmschulz** [comment]
I don't have any menu item to create the rooms - do I need the original talk to do that?

**Comment by sualko** [comment]
Please checkout your personal settings page :wink: and I guess this means we could enhance the workflow :joy:

**Comment by joergmschulz** [comment]
sounds better. But the room will not get created, and the browser console says:
xhr.js:178 POST https://nctest.faudin.de/apps/bbb/rooms 500
(anonymous) @ xhr.js:178
e.exports @ xhr.js:12
e.exports @ dispatchRequest.js:50
Promise.then (async)
l.request @ Axios.js:61
r.forEach.l.<computed> @ Axios.js:86
(anonymous) @ bind.js:9
(anonymous) @ Api.ts:24
c @ runtime.js:45
(anonymous) @ runtime.js:271
forEach.e.<computed> @ runtime.js:97
(anonymous) @ manager.js?v=936b306c-12:30
y @ manager.js?v=936b306c-12:30
value @ manager.js?v=936b306c-12:30
addRoom @ App.tsx:69
onSubmit @ NewRoomForm.tsx:13
u @ react-dom.production.min.js:14
d @ react-dom.production.min.js:14
(anonymous) @ react-dom.production.min.js:14
y @ react-dom.production.min.js:15
at @ react-dom.production.min.js:52
ot @ react-dom.production.min.js:51
ut @ react-dom.production.min.js:52
dt @ react-dom.production.min.js:56
D @ react-dom.production.min.js:287
B @ react-dom.production.min.js:19
Jt @ react-dom.production.min.js:70
Yt @ react-dom.production.min.js:69
t.unstable_runWithPriority @ scheduler.production.min.js:19
$o @ react-dom.production.min.js:122
j @ react-dom.production.min.js:287
Xt @ react-dom.production.min.js:68
createError.js:16 Uncaught (in promise) Error: Request failed with status code 500
    at e.exports (createError.js:16)
    at e.exports (settle.js:17)
    at XMLHttpRequest.d.onreadystatechange (xhr.js:61)

**Comment by sualko** [comment]
Can you check your nc log why this request failed?

**Comment by joergmschulz** [comment]
yes
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'INSERT INTO "oc_bbb_rooms" ("uid", "name", "welcome", "max_participants", "attendee_password", "moderator_password", "record", "user_id") VALUES(?, ?, ?, ?, ?, ?, ?, ?)' with params ["jpafk3LJ5bkWbQpG", "r1forjoergschulz", "", 0, "mP8R89RH7Hfp3KS9Y9AKk792bcXqpTdC", "ykwnQdpCnjbYpfH5mfkkRinGPE7yBfDL", false, "joerg.schulz"]: SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for type boolean: ""

**Comment by sualko** [comment]
Which db do you use?

**Comment by joergmschulz** [comment]
Postgres

**Comment by joergmschulz** [comment]
shouldn't I see more fields to be populated than just the room name?

**Comment by sualko** [comment]
For me this request looks good, but maybe postgres doesn't like `false` as boolean value.

> shouldn't I see more fields to be populated than just the room name?

Nope. That's all. An empty welcome message, no recording, no limit for participants, id and two passwords.

**Comment by joergmschulz** [comment]
I don't know. a manual insert with 'false'  worked: ```
INSERT INTO "oc_bbb_rooms" ("uid", "name", "welcome", "max_participants", "attendee_password", "moderator_password", "record", "user_id") 
VALUES('bbbbbbbbbb', 'greenbluebutton','', 0, 'bbbbbbbbbb', 'bbbbbbbbbb', 
	   false, 'joerg.schulz')
```

**Comment by sualko** [comment]
Would be nice if you could test my fix.

**Comment by joergmschulz** [comment]
will do - is this contained in the appstore or shall I pull it from git?

**Comment by joergmschulz** [comment]
now this works perfectly, thank you very much.
