### ISSUE TITLE
Change the Participantlimit after the Meeting was started once is not applied.

### ISSUE THREAD

**Issue by githubitm** [sualko/cloud_bbb#60]
**Describe the bug**
If I change the the Participantlimit for a Meeting. Changes are not applied.

**To Reproduce**
1. Go to Settings
2. Select "BigBlueButton" on the Left side.
3. Create a new room by entering the name of the room an click on "create"
4. Set a Max Value
5. Start the Meeting
6. Connect the count of Sessions you set in Max
6. Increase the Max Value
7. Try to Connect additional Sessions
8. You still get the Message "Error: The number of participants allowed for this meeting has been reached."

**Expected behavior**
Additional Sessions can be established.

**Screenshots**

![Screenshot from participantlimit reached](https://user-images.githubusercontent.com/19891706/89621016-e52c5700-d890-11ea-9a89-e760cdb0046b.png)
![Screenshot from 2020-08-06 17-25-18](https://user-images.githubusercontent.com/19891706/89621249-4c4a0b80-d891-11ea-9f05-23b32a9c4b5e.png)
![Screenshot from Participant-limit](https://user-images.githubusercontent.com/19891706/89621371-85827b80-d891-11ea-916c-edc28df0eb6e.png)

**System (please complete the following information):**
- Browser with version Firefox 79.0
- App version 0.5.1
- Nextcloud version 18.0.6
- BigBlueButton version 2.2.21
- Is your BigBlueButton instance working with Greenligh? yes
- Did you enter your BBB API url and secret? yes

**Comment by sualko** [comment]
BBB doesn't support configuration changes on the fly. You probably have to terminate the session, wait 15 minutes and try it again.

**Comment by sualko** [comment]
Any update on this?

**Comment by sualko** [comment]
I close this issue due to inactivity.
