### ISSUE TITLE
Nextcloud App: can't set recording setting for new Rooms

### ISSUE THREAD

**Issue by taw245de1ad** [sualko/cloud_bbb#64]
App:
  - bbb: 0.5.1

Nextcloud:   'version' => '18.0.7.1',
(ist mit 19 aber identisch)

Task: Create conference and activate recording in Settings -> Bigbluebutton

Expected behaviour: After creating the conference activating the recording
checkbox succeeds.

Actual behaviour: Recording checkbox is not selectable. This is also true for
setting max participants and maybe other values.

Workaround: activate any other page in the Settings, e.g. personal
information. When going back to bigbluebutton the recording checkbox is
changeable.

**Comment by sualko** [comment]
I can confirm this behavior and here is the related Nextcloud log entry:

```
[index] Error: Exception: Argument 6 passed to OCA\BigBlueButton\Controller\RoomController::update() must be of the type string, null given, called in /var/www/wolke.herberth.eu/lib/private/AppFramework/Http/Dispatcher.php on line 170 at <<closure>>

PUT /apps/bbb/rooms/5
```
