### ISSUE TITLE
Allow NextCloud admin to clean up unused/old rooms

### ISSUE THREAD

**Issue by u451f** [sualko/cloud_bbb#66]
I'm have a BBB server with Greenlight and a NextCloud server with the bbb plugin.
On Greenlight, as an admin, I can see all the rooms and recordings of people, and potentially delete unused rooms, and old recordings. When using bbb with NextCloud, it would be great to allow NextCloud admins a supplementary interface where one can see the rooms that have been created on the BBB server to potentially clean some of them. 

Also, if I delete a user from NextCloud, would that clean the rooms on the BBB server that this user has created?

**Comment by sualko** [comment]
In my opinion this is not needed, because "unused" rooms don't consume any server resources. If you create a room in Nextcloud, this doesn't affect your BBB instance. It only costs you one db row on your NC. Therefore this feature will not be integrated by me.
