### ISSUE TITLE
Datetime format bug

### ISSUE THREAD

**Issue by shimmy11** [sualko/cloud_bbb#7]
Dear sualko,
thanks for working on the app! Didnt realize I discovered it within the first hours of original submit.
I receive the following bug when setting up a room, according to nextcloud.log:

SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect integer value: '' for column `nextcloud`.`oc_bbb_rooms`.`record` at row 1","Code":0,"Trace":[{"file":"/*redacted path*/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php","line":169,"function":"convertException","class":"Doctrine\\DBAL\\Driver\\AbstractMySQLDriver","type":"->","args":["An exception occurred while executing 'INSERT INTO `oc_bbb_rooms` (`uid`, `name`, `welcome`, `max_participants`, `attendee_password`, `moderator_password`, `record`, `user_id`) VALUES(?, ?, ?, ?, ?, ?, ?, ?)' with params ...

**Comment by sualko** [comment]
Guess it's a similar bug as in #6. I run this app on three instances and encountered no errors, but I guess your setup is different. I will try to setup some testing and resolve those bugs in the next release. If you have time it would be great if you could debug this a bit more.

**Comment by langfingaz** [comment]
Hey,

I have a similar error when trying to create a room.

About my setup:
```
NextCloudPi version  v1.25.0
NextCloudPi image    NextCloudPi_docker_04-05-20
distribution         Debian GNU/Linux 10 \n \l
Nextcloud version    18.0.4.2
```

And the error message:

```
[index] Error: Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'INSERT INTO `oc_bbb_rooms` (`uid`, `name`, `welcome`, `max_participants`, `attendee_password`, `moderator_password`, `record`, `user_id`) VALUES(?, ?, ?, ?, ?, ?, ?, ?)' with params ["2iHMcT7RcrepfSSy", "ncpTest", "", 0, "abB4CEWAMQ6RkesBz5K39rronoyLT4cL", "3iyqd9QJt39yG73CecZjfwBwDeLg5psJ", false, "ncp"]:

SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect integer value: '' for column `nextcloud`.`oc_bbb_rooms`.`record` at row 1 at <<closure>>
...
POST /apps/bbb/rooms
```

I hope this helps you!

**Comment by sualko** [comment]
Would be nice if you could test my fix.

**Comment by shimmy11** [comment]
Thanks - seems to work now!

**Comment by langfingaz** [comment]
Thanks for the quick reply! I didn't manage to build from the git version in my nextcloudpi docker, so could not test it and will wait for an update in the NC app store ;)
