### ISSUE TITLE
Server error on 1.0.1 version

### ISSUE THREAD

**Issue by frankbootmaker** [sualko/cloud_bbb#70]
**Describe the bug**
Opening the user control panel a "server error" is being displayed.
A room could be created and started but it won't be saved.

**To Reproduce**
1. Go to 'BigBlueButton user control panel' , it shows server error at the beginning of the line
2. Click on 'create new room'
3. Additional line is created, if you click on launch the room the meeting in BBB will start, but the 
   "server error"line still exist.
4. Once navigating away from the BigBlueButton configuration board and coming back the earlier created room is vanished.

**Expected behavior**
No error message appears and the created rooms do stay in the list

**Screenshots**
![kép](https://user-images.githubusercontent.com/32898636/91976847-e7fc5980-ed21-11ea-8186-8b4ca10035b7.png)

![kép](https://user-images.githubusercontent.com/32898636/91977106-69ec8280-ed22-11ea-80a6-e576fbbcfebf.png)

![kép](https://user-images.githubusercontent.com/32898636/91976847-e7fc5980-ed21-11ea-8186-8b4ca10035b7.png)

**System (please complete the following information):**
 - Browser with version [e.g. chrome, safari]
   Firefox, Chrome, Edge
 - App version [e.g. 0.1.0]
   1.0.1
 - Nextcloud version [e.g. 18.0.1]
   18.0.8
 - BigBlueButton version [e.g. 2.2.9]
   2.2.0
   
 - Is your BigBlueButton instance working with Greenligh? yes/no
   yes
 - Did you enter your BBB API url and secret? yes/no
   yes

**Nextcloud log:**
 No
```
REPLACE ME WITH YOUR NEXTCLOUD LOG
```

**Javascript log:**
 No
```
REPLACE ME WITH YOUR JS LOG
```

**Additional context**

**Comment by nervnet65** [comment]
Had the same problem. After deactivating the circles-app it works.

**Comment by frankbootmaker** [comment]
Indeed, after deactivating circles all previously created meeting rooms are there:

![kép](https://user-images.githubusercontent.com/32898636/91981243-ceaadb80-ed28-11ea-9492-533dbd7e53b1.png)

There shall be a conflict with circles...

**Comment by sualko** [comment]
Thanks for your bug report.

> A room could be created and started but it won't be saved.

Frankly that's not possible. Please describe this in more detail.

> Nextcloud log: No

Please set your log level to debug (0) and look for related entries, because otherwise I have no possibility to resolve this issue. It would also be helpful if you could check the network tab, of your dev console, for requests which results in a error and are related to this app.

**Comment by frankbootmaker** [comment]
Hi Sualko, 

it is as described, and nervnet65 gave the hint, if circles is turned off all created rooms will be visible again.
Please see me note just above where you could see all the created rooms I did for the testing.

If I turn back circles the list of rooms will disappear again and only the error remains.

![kép](https://user-images.githubusercontent.com/32898636/91982175-2564e500-ed2a-11ea-9e59-7d94b070760d.png)

(Kiszolgálóhiba means server error)

**Comment by sualko** [comment]
> it is as described

A description without an error message is not helpful for any developer. Therefore please help to save some time and provide a proper error message next time. I enabled the circle app in one of my production instances with NC 18 and had a nice log entry:

```
Exception: Undefined class constant 'CIRCLES_ALL'
```

Oh boy. The circle teams changed the api without a major version bump. NC 18 gets version 0.18.9 which has a different api than 0.19.x (shipped for NC 19). Can you try to replace https://github.com/sualko/cloud_bbb/blob/master/lib/CircleHelper.php#L44 with

```
$circles = $api->listCircles(\OCA\Circles\Model\Circle::CIRCLES_ALL, '', \OCA\Circles\Model\Member::LEVEL_MEMBER);
```

and see if it works?

**Comment by frankbootmaker** [comment]
Yes, it fixed it! 👍 

![kép](https://user-images.githubusercontent.com/32898636/91983440-f2235580-ed2b-11ea-89b7-a36f31bcbe3b.png)

**Comment by sualko** [comment]
> Yes, it fixed it!

Thanks for testing.
