### ISSUE TITLE
Group search in restictions finds only groups of which I am a member

### ISSUE THREAD

**Issue by nervnet65** [sualko/cloud_bbb#71]
**Describe the bug**
To add a restriction, the group search only shows the groups I am a member of. As an administrator, I want to set the restriction for other groups as well. Workaround: Add yourself to the group, add a restriction, remove yourself from the group.

**To Reproduce**
1. add a group and do not add yourself to the group
2. try to set a restriction for this group
3. it is not possible to select this group

4. add yourself to the group.
5. try to set a restriction for this group
6. now it is works

**Expected behavior**
As an administrator, I can add a restriction for each group, regardless of whether I am a member of the group or not.

**System (please complete the following information):**
 - Browser with version Firefox 80.0.1 64bit Windows
 - App version 1.0.1
 - Nextcloud version 18.0.8
 - BigBlueButton version 2.2.0
 - Is your BigBlueButton instance working with Greenligh? yes
 - Did you enter your BBB API url and secret? yes

**Nextcloud log:**
No errors.

**Javascript log:**
No errors.

**Comment by sualko** [comment]
We use the same api as the share service, so all share restrictions are applied as well. You probably don't allow users to share files with groups they were not part of. A workaround therefore is to disable the "Restrict users to only share with users in their groups" option in your admin settings, set the restriction and enable the option again. It's only a workaround, but it should work for most users.
