### ISSUE TITLE
After upgrade to 1.0.1 rooms are disappearing

### ISSUE THREAD

**Issue by Brada65** [sualko/cloud_bbb#72]
**Describe the bug**
All BBB rooms that are created previously with this application on NC doesn't exist anymore after upgrade.

**To Reproduce**
1. Go to 'User>Settings'
2. Click on 'BigBlueButton' on the left sidebar
3. Application main space is showing 'Server error'
4. User can create new room, and with clickon play icon start it (BBB is working)
5. Go to the 'Personal info'
6. Go to the 'BigBlueButton' again and room doesn't exist anymore

**Expected behavior**
Application main space should show list of BBB rooms created with all settings and recordings related (if they exists).
**Screenshots**
![image](https://user-images.githubusercontent.com/22346041/92140376-61aa4b00-ede7-11ea-99e5-e928e7900c16.png)

**System (please complete the following information):**
 - Browser with version - Firefox 80.0.1 (and all other browsers)
 - App version - 1.0.1
 - Nextcloud version - 18.0.4
 - BigBlueButton version - BBB Cloud service
 - Is your BigBlueButton instance working with Greenligh? YES
 - Did you enter your BBB API url and secret? YES

**Nextcloud log:**

```

	Exception: Undefined class constant 'CIRCLES_ALL'

 0. /var/www/html/nc/lib/private/AppFramework/App.php - line 125:

     OC\AppFramework\Http\Dispatcher->dispatch(OCA\BigBlueB ... {}, "index")

 1. /var/www/html/nc/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47:

    OC\AppFramework\App::main("OCA\\BigBlu ... r", "index", OC\AppFramew ... {}, { _route: "bbb.room.index"})

 2. <<closure>>

    OC\AppFramework\Routing\RouteActionHandler->__invoke({ _route: "bbb.room.index"})

 3. /var/www/html/nc/lib/private/Route/Router.php - line 299:

    call_user_func(OC\AppFramew ... {}, { _route: "bbb.room.index"})

 4. /var/www/html/nc/lib/base.php - line 1008:

    OC\Route\Router->match("/apps/bbb/rooms")

 5. /var/www/html/nc/index.php - line 38:

    OC::handleRequest()
	

Caused by Error: Undefined class constant 'CIRCLES_ALL'

 0. /var/www/html/nc/apps/bbb/lib/Controller/RoomController.php - line 62:

    OCA\BigBlueButton\CircleHelper->getCircleIds("ccowie")

 1. /var/www/html/nc/lib/private/AppFramework/Http/Dispatcher.php - line 170:

    OCA\BigBlueButton\Controller\RoomController->index()

 2. /var/www/html/nc/lib/private/AppFramework/Http/Dispatcher.php - line 99:

    OC\AppFramework\Http\Dispatcher->executeController(OCA\BigBlueB ... {}, "index")

 3. /var/www/html/nc/lib/private/AppFramework/App.php - line 125:

    OC\AppFramework\Http\Dispatcher->dispatch(OCA\BigBlueB ... {}, "index")

 4. /var/www/html/nc/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47:

    OC\AppFramework\App::main("OCA\\BigBlu ... r", "index", OC\AppFramew ... {}, { _route: "bbb.room.index"})

 5. <<closure>>

    OC\AppFramework\Routing\RouteActionHandler->__invoke({ _route: "bbb.room.index"})

 6. /var/www/html/nc/lib/private/Route/Router.php - line 299:

    call_user_func(OC\AppFramew ... {}, { _route: "bbb.room.index"})

 7. /var/www/html/nc/lib/base.php - line 1008:

    OC\Route\Router->match("/apps/bbb/rooms")

 8. /var/www/html/nc/index.php - line 38:

    OC::handleRequest()
```

**Javascript log:**

```
REPLACE ME WITH YOUR JS LOG
```

**Additional context**
Click on the 3 dots of file is showing menu, but without room created.

**Comment by sualko** [comment]
Thanks for that nice bug report. Your issue has already been fixed and will be shipped with the next release. See #70 for details.
