### ISSUE TITLE
User/group drop down not clickable

### ISSUE THREAD

**Issue by sualko** [sualko/cloud_bbb#73]
on the additional settings page, it is possible to add properties for groups.
This does not work in all cases; I have seen it work using Edge on Windows, but not on any other browsers like Firefox for windows, mac; safari for mac; chrome for windows& mac.

When I start to type in names of grops, the full name of the group appears as expected.
Even a list of all groups starting with the same letters appears.
<img width="241" alt="grafik" src="https://user-images.githubusercontent.com/6523646/92277465-4c224780-eef3-11ea-918f-f8ee672c4b24.png">

When I click on one of thse groups, nothing happens in all of these browsers.
In Edge, the group gets selected and added to the group properties list.

Using the network tab of the browser console, I see quite some messages arriving in Edge, but NONE in the other browsers. It is as if the click wouldn't arrive. When I drag the mouse, not the text in the list window gets selected, but the text in the next line. When I do that in Edge, no text gets selected (as maybe expected).

_Originally posted by @joergmschulz in https://github.com/sualko/cloud_bbb/issues/69#issuecomment-685733280_

**Comment by joergmschulz** [comment]
just noticed that there is one difference in look and feel - the yellow marked X in below picture is visible in Edge, but not the other browsers:
![grafik](https://user-images.githubusercontent.com/6523646/94060319-0ff05180-fde4-11ea-98ec-d641093dc45e.png)

**Comment by sualko** [comment]
I found a way to block the blur event if the list is clicked and therefore I hope this issue is fixed now. We will release a beta version soon and it would be nice if you could help to test this.

**Comment by joergmschulz** [comment]
That's beautiful. Thank you again. Is this already available in master?

**Comment by sualko** [comment]
It is, but if you want to cherry pick you also have to build it by your own.

**Comment by joergmschulz** [comment]
pulled master, built it, waited for caches to emtpy / tried with FFox(Mac), Chrome (Mac), Edge (Windows), works perfectly now on the second attempt on every one of these browsers!

**Comment by sualko** [comment]
I'm relieved that this annoying issue is resolved now. Thanks for testing :clap:

**Comment by joergmschulz** [comment]
welcome. just give me a hint when something else can be tested.

**Comment by sualko** [comment]
If you have time it would be great if you could test the latest beta release: https://github.com/sualko/cloud_bbb/releases/tag/v1.1.0-beta.1

**Comment by joergmschulz** [comment]
did some tests / issues have been created. Could not yet test behaviour on user deletion nor scalelight. User deletion will be tested some time soon, will get interesting because I've got a LDAP environment.
