### ISSUE TITLE
l10n: There is no translation in Transifex

### ISSUE THREAD

**Issue by Valdnet** [sualko/cloud_bbb#78]
There is no translation of the text string in Transifex:
`'This room is not open yet. We will try it again in %n seconds. Please wait.'`

You should change this code:
https://github.com/sualko/cloud_bbb/blob/1f8a393e14612dc0e5692c22dc3798713de8ab40/ts/waiting.ts#L8-L13

for the nextcloud-bot to scan it properly.

Note that in other languages ​​the word is changed in **three** types, for example:

> 1 sekund**a**
> 2 sekund**y**
> 5 sekund

**Comment by sualko** [comment]
> You should change this code

I guess it's the type hint. Or do you think it's the newline?

**Comment by sualko** [comment]
Found the proper documentation in the code. 

https://github.com/nextcloud/server/blob/a2a3b87c19662f06cfb804b9fead7e939b1c3e6c/core/src/globals.js#L139-L148

Thanks for your help again.
