### ISSUE TITLE
State of rooms in room table

### ISSUE THREAD

**Issue by jpk6789** [sualko/cloud_bbb#79]
It would be nice if the state of a room (running, not running) is displayed in the table of all rooms. In my opinion, there could be two possible representations for it. First, this state could be displayed in a new row in text form. The other solution could be to change the "Play" icon of the room link. I would prefer the second solution or a combination of both.

Possible solution:
![grafik](https://user-images.githubusercontent.com/7957707/92591275-e55bb000-f29d-11ea-930a-786a790f6f9b.png)

**Comment by sualko** [comment]
Thanks for this feature request. Following I will collect my thoughts for a possible implementation.

- switching the button could serve as start/abort
  - we need a way to join the room if the room is running
- we need the room state at multiple places
  - overview table
  - require moderator
  - start with presentation
- native approach needs one BBB API request every time the state is needed
- push approach with [webhooks](https://docs.bigbluebutton.org/dev/webhooks.html)
  - bad documentation
  - no filter for event types
  - need admin option to recreate hooks
  - hooks have to be deleted once the app is removed
  - does it work with scalelight?
- push approach with [callback](https://docs.bigbluebutton.org/dev/api.html#end-meeting-callback-url)
  - easy to implement
  - is it reliable? Do we need a fallback?
