### ISSUE TITLE
Add more format for integration in nextcloud

### ISSUE THREAD

**Issue by Ludovicis** [sualko/cloud_bbb#8]
Can you add more file extension in file manager of nextcloud please ? Thanks
As this picture (From my bigbluebutton instance)
![image](https://user-images.githubusercontent.com/16205280/80384383-1ade9e80-88a5-11ea-9d19-88cba0afd101.png)

**Comment by sualko** [comment]
You can add the mime types here https://github.com/sualko/cloud_bbb/blob/master/ts/filelist.ts#L22 and create a pull request on github.

**Comment by Ludovicis** [comment]
I try to add mime type with this link:
https://developer.mozilla.org/fr/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types

    const mimeTypes = [
        'application/pdf',
        'application/vnd.oasis.opendocument.presentation',
        'application/vnd.oasis.opendocument.text',
        'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        'application/vnd.openxmlformats-officedocument.presentationml.presentation',
        'application/vnd.oasis.opendocument.presentation',
        'application/vnd.oasis.opendocument.spreadsheet',
        'application/msword',
        'application/vnd.ms-powerpoint',
        'application/vnd.ms-excel',
        'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        'image/jpeg',
        'image/png',
        'application/vnd.ms-powerpoint',
    ];

I have add jpg, png xls, xlsx and ppt but no change in nextcloud file manager ...

**Comment by Ludovicis** [comment]
OK i can't open a new pull request, sorry.

    const mimeTypes = [
        'application/pdf',
        'application/vnd.oasis.opendocument.presentation',
        'application/vnd.oasis.opendocument.text',
        'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        'application/vnd.openxmlformats-officedocument.presentationml.presentation',
        'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        'application/vnd.oasis.opendocument.presentation',
        'application/vnd.oasis.opendocument.spreadsheet',
        'application/msword',
        'application/vnd.ms-powerpoint',
        'application/vnd.ms-excel',
        'image/jpeg',
        'image/png',
        'text/plain',
        'text/rtf',
];

Mimetype find here:
https://github.com/nextcloud/server/blob/master/resources/config/mimetypemapping.dist.json

A do a new make build from app direcctory and now it's ok.

**Comment by sualko** [comment]
Thanks :clap:
