### ISSUE TITLE
release 1.1.0-beta 1 / activity not working. 

### ISSUE THREAD

**Issue by joergmschulz** [sualko/cloud_bbb#84]
While entering the Activities, the NC log displays:
```[PHP] 
Error: Undefined index: shareWith at /www/nextcloud/custom-apps/bbb/lib/Activity/Provider.php#135

GET /ocs/v2.php/apps/activity/api/v2/activity/all?format=json&previews=true&since=0
from 192.168.176.17 by joerg.schulz at 2020-09-24T14:16:31+00:00
```

Additionally, the activity windows stays empty.

Probably the upgrade process failed? How can this index be added?

**Comment by joergmschulz** [comment]
not sure, maybe I have to do more? 
[PHP] Error: Undefined index: shareType at /www/nextcloud/custom-apps/bbb/lib/Activity/Provider.php#152

GET /ocs/v2.php/apps/activity/api/v2/activity/all?format=json&previews=true&since=0
from 192.168.176.16 by joerg.schulz at 2020-09-28T13:07:35+00:00

**Comment by sualko** [comment]
You have to delete some rows in the activity table. The easiest thing is if you delete all entries from the bbb app.

**Comment by joergmschulz** [comment]
Correct. After deleting rows from activity it worked. ```delete
	FROM public.oc_activity 
	where app = 'bbb';```
