### ISSUE TITLE
release 1.1.0-beta 1 / password not displayed on room creation

### ISSUE THREAD

**Issue by joergmschulz** [sualko/cloud_bbb#85]
When I create a room and enter the properties window, the option Internal + Password is defaulted, but the password is not displayed. It will only be displayed when I change this to another option and back again.

The password should be displayed immediately. Or another option should be default.

**Comment by sualko** [comment]
Do you have any restrictions in place? Did it work with 1.0?

**Comment by joergmschulz** [comment]
Indeed.
This happens only when the restriction 'not public' is in place: all options enabled except public. Then, the first item in the list is the one with password restriction, and the password is not shown initially. 

Can't reproduce in 1.0 because new created rooms don't obey the restrictions in my browser (public displayed even if I'm not allowed to create a Public room). That's fixed in 1.1.0-beta 1

**Comment by joergmschulz** [comment]
confirming. deactivate app, git pull && make build, activate app and it works. Perfect, thank you for this fix. I think I have tested all I could test in my environment in my timeframe (open: deletion of users in LDAP).

**Comment by sualko** [comment]
> I think I have tested all I could test in my environment in my timeframe

Thanks a lot. Testers are valuable and therefore always welcome. I have to extend the ci test to NC 20 and than we are ready to release it. Probably tomorrow.
