### ISSUE TITLE
Share room list / share some rooms and/or access to the room recordings

### ISSUE THREAD

**Issue by lars-becker** [sualko/cloud_bbb#86]
For groups or organisations it would be helpful to make it possible to share the administration of rooms or at least the access to the recordings else no one will be able to make changes if the managing person is absent etc.

**Comment by sualko** [comment]
This has already been implemented. Add a user or group as moderator and click on the share icon. If you have an idea how this could be more clear to users, I appreciate every two cents.

**Comment by lars-becker** [comment]
Ah, great. Sorry, I haven't found it.  Maybe adding one sentence in the modal? But when one knows it it pretty obvious. But what about recordings? Maybe one would like to share the access? Maybe a dedicated "sharing" section where one can share access an/or to recordings?
