### ISSUE TITLE
404 and 401 issues after upgrade to 1.1

### ISSUE THREAD

**Issue by ajs124** [sualko/cloud_bbb#90]
**Describe the bug**
After upgrading the app to 1.1 some room links, seemingly ones for `waiting_room` rooms, but not for `internal` rooms, cannot be connected to anymore.

Were there any changes in how the BBB API is called?

**To Reproduce**
1. Click on a link to a room with 1.0.x with waiting enabled, observe it works.
2. Click on a link the same link with 1.1.x and observe it does not anymore.

**Expected behavior**
Same behavior on 1.1 as on 1.0.

**Screenshots**
A 404 screen from nginx and a 401 from bbb-html5. I did not screenshot them, but there was nothing more on them.

**System (please complete the following information):**
 - Browser with version: latest FireFox and Chromium releases, but most likely irrelevant
 - App version: 1.1.0
 - Nextcloud version: 19.0.3
 - BigBlueButton version: 2.2.23
 - Is your BigBlueButton instance working with Greenlight? yes
 - Did you enter your BBB API url and secret? yes

**Javascript log:**

Only from bbb-html5, which failed to connect to meteor.

**Additional information:**
The 404 errors were from bbb-web redirecting to a wrongly configured URL. Fixing that config does however not fix the 401 issues.
The config was also "broken" before, but this part of it was seemingly never used?
The change in config to fix the 404 can be seen here: https://github.com/helsinki-systems/bbb4nix/pull/65/files

**Comment by sualko** [comment]
> Were there any changes in how the BBB API is called?

We updated the [BBB PHP API](https://github.com/littleredbutton/bigbluebutton-api-php/releases) from 3.0 to 3.2, but there were no breaking changes.

Currently I have problems to understand from which server those errors come from. Please open your dev console, go to the network tab, enable "preserve log" (or similar), try to join a room and provide the url "chain" until one of the errors arise. If you replace the urls, please try to make sure that it's clear which services is running behind a domain. E.g. secret-cloud.com -> nextcloud.local.

**Comment by ajs124** [comment]
Hm, ok. I'll look through the changes there, then. Would version 1.1 of cloud_bbb also work with version 3.0 of the bbb php api (for testing purposes) or did you need to adapt your code to the new version of the library?

I'll try and get back to you with some logs soon. I currently don't have an instance to test this on, ready to go, as the instance where I saw this is used productively, so I just downgraded for now.

The actual 401 error codes are generated by bbb-html5.

**Comment by sualko** [comment]
> Would version 1.1 of cloud_bbb also work with version 3.0 of the bbb php api 

Should work with the fork from littleredbutton (link above).

**Comment by ajs124** [comment]
It only occurs with version 3.2 of bbb-php-api, so for now I'm running it with [this commit](https://github.com/ajs124/cloud_bbb/commit/75397e7a756225c9c09b52cb4164df927f7ff556).

The only real difference in URLs seems that `guest=false` is not passed on anymore, which is because of https://github.com/littleredbutton/bigbluebutton-api-php/commit/4f9e381e70861c7ef3d59bdb7331c3e582c58401

Neither the commit itself neither [the corresponding PR](https://github.com/littleredbutton/bigbluebutton-api-php/pull/37) give any reason as to why this is the case now.

The only relevant part of the URL "chain" already starts on BBB. With 3.0 or 3.1 it looks like this:
```
https://bbb.local/bigbluebutton/api/join?meetingID=SOME_MEETING_ID&fullName=TEST_USER_NAME&password=SUPER_SECRET_PASSWORD&userID=SAME_AS_FULL_NAMEroot&createTime=1603041115852&redirect=true&joinViaHtml5=true&guest=false&checksum=SOME_CHECKSUM
https://bbb.local/html5client/join?sessionToken=SESSION_TOKEN
https://bbb.local/html5client/sockjs/info?cb=IDK_WHAT_THIS_IS
wss://bbb.local/html5client/sockjs/082/NO_IDEA_EITHER/websocket
https://bbb.local/bigbluebutton/api/enter?sessionToken=SESSION_TOKEN
https://bbb.local/html5client/locale?locale=de-DE&init=true
```

With 3.2 the first request doesn't have `guest=` as a get parameter, as outlined above.
This leads to the `sockjs` URL and `wss://` websocket being repeatedly called and eventually giving up.
The console meanwhile repeatedly says `Object { error: 401, description: "Authentication timeout." }`.

All in all, this is most likely a bug in the API library you're using and not your project. Should I open a bug over there?

**Comment by sualko** [comment]
This app and also the library is just in plenty of projects, so it is a bit weird, that there should be a issue, but if you open a related issue over there, I hope we can fix it soon.
