### ISSUE TITLE
context menu upload buggy after NC20 upgrade

### ISSUE THREAD

**Issue by cjhille** [sualko/cloud_bbb#92]
Before on NC19 I was able to upload documents to the BBB instance. After the upgrade none of the rooms (for any user) show up in the context menu (cleared browser cache etc.), while the rooms are setup properly and usable in the configuration page.

App version 1.1.0
NC version 20.0.0
BBB version 2.2.27 https://github.com/alangecker/bigbluebutton-docker

There are no related nextcloud log or browser console entries. 

EDIT: 
The issue seems to be weirdly related to browser caching. I had the option "disable cache" in chrome dev tools set to true and the rooms never showed up. Once I disabled this, they rooms appeared after refreshing the page. However after clicking a room name I'm prompted with "internal servererror":
```
Exception: Can not process create request: https://konferenz.REDACTED.de/bigbluebutton/api/create?name=Konferenzraum&meetingID=xaF7PoiNMiYCnP98&attendeePW=esrRg22wxHHgtH6aLeTy8Zc8sBiobL8A&moderatorPW=a6ZNPAcNFnbxdaZwWPyRLbgCMtSEtsZB&logoutURL=https%3A%2F%2Fcloud.REDACTED.de&record=true&maxParticipants=50&autoStartRecording=false&allowStartStopRecording=true&moderatorOnlyMessage=Um+jemanden+zu+dem+Termin+einzuladen+schicke+ihm+diesen+Link%3A+https%3A%2F%2Fcloud.REDACTED.de%2Fapps%2Fbbb%2Fb%2FxaF7PoiNMiYCnP98&webcamsOnlyForModerator=false&muteOnStart=false&guestPolicy=ALWAYS_ACCEPT&lockSettingsDisableCam=false&lockSettingsDisableMic=false&lockSettingsDisablePrivateChat=false&lockSettingsDisablePublicChat=false&lockSettingsDisableNote=false&lockSettingsHideUserList=false&lockSettingsLockedLayout=false&lockSettingsLockOnJoin=true&lockSettingsLockOnJoinConfigurable=false&allowModsToUnmuteUsers=false&meta_endCallbackUrl=https%3A%2F%2Fcloud.REDACTED.de%2Fapps%2Fbbb%2Fhook%2Fended%2FxaF7PoiNMiYCnP98%2F7XXa9pJXSTUTxVyuwdgnx2V9Kqs&meta_bbb-recording-ready-url=https%3A%2F%2Fcloud.REDACTED.de%2Fapps%2Fbbb%2Fhook%2Frecording%2FxaF7PoiNMiYCnP98%2F7XXa9pJXSTUTxVyuwdgnx2V9Kqs&checksum=ab25220cd39340dce5826b44dcce0ce4be091b0b
```
Note: The rooms themselves work fine. It's just the upload that seems to fail now. And it worked before with NC19

**Comment by sualko** [comment]
Thanks for your bug report. I can confirm the issue and there will be a fix asap.
