### ISSUE TITLE
Strange behaviour in App-List

### ISSUE THREAD

**Issue by configonfi** [sualko/cloud_bbb#96]
This App works really fine, but I perceive a strange behaviour when I set the checkmark at **"Die Raumverwaltung in der App-Navigation anstelle der Einstellungsseite anzeigen."** This option is really great for having an easy and clear access to my conference-rooms. I don't want to miss it!

The Issue is: The App-Icon is only shown, wenn I click on "my profile" =>  "option": 
<img width="161" alt="bbb_2" src="https://user-images.githubusercontent.com/65956920/97362126-d0180080-18a0-11eb-9093-449eea2e46c8.png">

When I click on any other App (Files, Talk, … ) the BBB-App-Icon is invisible: 
<img width="130" alt="bbb_1" src="https://user-images.githubusercontent.com/65956920/97362124-d0180080-18a0-11eb-9111-04a3db46cd03.png">

If you are familiar with this behaviour its OK. Pretty unconvenient but not a big thing. But I know a lot of users who are unsettled whit that.

Tested with NC 19.0.3 and BigBlueButton Integration V 1.1.0

Thanks for help and greetings, configonfi

**Comment by sualko** [comment]
Thanks for your bug report. I can confirm your issue and will provide a fix asap.

**Comment by sualko** [comment]
I was able to reproduce it only one time. Now it's working on all my instances. Do you have still this issue?

**Comment by configonfi** [comment]
> I was able to reproduce it only one time. Now it's working on all my instances. Do you have still this issue?

Hello sualko, 

unfortunately yes! I have testet your update 1.1.1 on two commercial installations (Hetzner) and get exactly the same behaviour. I also tried to disable some other Apps (for exampel "App-Order") to find out the root cause … without any success.

Thanks for your efforts, configonfi

**Comment by Nyco** [comment]
We have a Nextcloud 19.0.4 with BigBlueButton Integration 1.1.1, with the same option checked.

Indeed, we confirm the app icon/button disappears... sometimes! :)

# Test case

## Context
- we have more than 7 apps enabled in the top bar, so we have the plus "..." drop-down menu for more apps
- we have enabled the AppOrder app

## Icon/button disappearing
GIVEN I have the BBB icon/button
WHEN I click on any other icon/button
THEN the BBB icon/button disappears

## Icon/button reappearing
GIVEN I DON'T have the BBB icon/button
WHEN I click on the Paramaters icon/button
THEN the BBB icon/button reappears

## Note
The AppOrder repository has no "BBB" issue so far

**Comment by sualko** [comment]
Can someone try to apply the fix from 7f884da manually? That would be awesome!

**Comment by tron65** [comment]
i have the same problem in our installation, i applied the fix, and can confirm that it works, both on nextcloud 18.0.6 and 19.0.4, the app-icon does not disappear anymore, i would definitely be happy, if the fix is merged.

**Comment by sualko** [comment]
@tron65 thanks for testing. I will merge the fix asap.
