### ISSUE TITLE
Display in the unreadable record submenu with dark themes

### ISSUE THREAD

**Issue by Ludovicis** [sualko/cloud_bbb#98]
**Describe the bug**
Display in the unreadable record submenu with dark themes (Same problem with Breeze Dark Theme and official Nextcloud dark theme on accessibility personnal setting)

Bug issue also on Netcloud Breeze Dark app:
https://github.com/mwalbeck/nextcloud-breeze-dark/issues/139

**To Reproduce**
1. Go to big blue nextcloud app
2. Click on up arrow recording

**Expected behavior**
Maybe change the up arrow icon with this record icon here; more clear for me:
https://fontawesome.com/icons/video?style=solid
And change background color to match the general presentation of the application, and to be able to read the recording line.

**Screenshots**
Before to click on up arrow icon:
![image](https://user-images.githubusercontent.com/16205280/98302233-537dd400-1fbc-11eb-8e45-f10a5cad59df.png)
After to click on up arrow icon:
![image](https://user-images.githubusercontent.com/16205280/98301733-8e333c80-1fbb-11eb-9cdd-4ae5d232bebe.png)
For read
![image](https://user-images.githubusercontent.com/16205280/98301794-a5722a00-1fbb-11eb-8002-fb21ad5ae279.png)

**System (please complete the following information):**
 - chrome Version 86.0.4240.111 (Build officiel) (64 bits)
 - App version BigBlueButton Integration 1.1.1
 - Nextcloud version 20.0.1
 - Is your BigBlueButton instance working with Greenligh? yes
 - Did you enter your BBB API url and secret? yes

Thanks,

**Comment by sualko** [comment]
Should work in light and dark mode now.

![2020-11-24 11 43 36 localhost c4493b86790a](https://user-images.githubusercontent.com/2974196/100084031-8b08cf00-2e4a-11eb-94bf-944982584b21.png)

![2020-11-24 11 44 24 localhost fd8f12242d22](https://user-images.githubusercontent.com/2974196/100084046-90661980-2e4a-11eb-9a64-ee8474b7674f.png)
